//! Chat orchestration. Every user message follows the same pipeline:
//!
//! ```text
//! user message
//!   → attached / named files first (Deep), then the selected Shelf
//!     whole extracted files when they fit the local-context budget,
//!     otherwise search; hits include nearby text
//!     Light / Deep: extra search queries fused in
//!     Deep: more of each top matching file when they fit;
//!          cheapest native model thinking when the template supports it
//!   → Retrieval Gate
//!   → local AI (house rules · shelf file index · original message · recent context · gated sources)
//!     The AI may search the Shelf again, read more around a citation,
//!     open a named file (one window at a time), or search earlier conversations
//!   → streamed answer with citations
//! ```
//!
//! Every answer is generated by the local model; search only supplies
//! source material when the files are too long to send whole.

mod avatars;
pub mod conversations;
mod focus;
mod neighbors;
mod prompts;
mod queries;
mod tools;

use anyhow::{anyhow, Result};
use serde_json::json;
use std::collections::{HashMap, HashSet};
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};

use crate::core::Ctx;
use crate::engine::{
    ChatMessage, ChatOptions, ChatOutput, ChatThinking, Engine, StreamEvent, ToolCall,
};
use crate::search::{fold_ws, gate};
use crate::shelf::ThinkLevel;
use crate::types::{DocStatus, DocumentMeta, SourcePassage};
use conversations::{Conversations, StoredMessage};
use prompts::{
    build_system_prompt, format_citation_legend, format_retrieved_context, format_shelf_inventory,
    guess_message_lang, sanitize_citations, shelf_file_labels,
};
use queries::extra_search_queries;

const HISTORY_MAX_MESSAGES: usize = 12;
const HISTORY_MAX_CHARS: usize = 6_000;
const HISTORY_MESSAGE_MAX_CHARS: usize = 4_000;

/// Local chat pipeline: retrieve, prompt, stream, and persist.
pub struct ChatService {
    ctx: Arc<Ctx>,
    engine: Arc<Engine>,
    cancels: Mutex<HashMap<String, Arc<AtomicBool>>>,
    /// One in-flight generation for the whole app. A second send waits here.
    generation: tokio::sync::Mutex<()>,
}

impl ChatService {
    pub fn new(ctx: Arc<Ctx>, engine: Arc<Engine>) -> Arc<Self> {
        Arc::new(Self {
            ctx,
            engine,
            cancels: Mutex::new(HashMap::new()),
            generation: tokio::sync::Mutex::new(()),
        })
    }

    pub fn cancel(&self, message_id: &str) {
        if let Some(flag) = crate::core::mutex_lock(&self.cancels).get(message_id) {
            flag.store(true, Ordering::Relaxed);
        }
    }

    /// Unlock the UI when `send_message` returns before it could emit `done`.
    pub(crate) fn notify_send_failed(&self, thread_id: &str) {
        self.ctx.events.emit(
            "rebost://chat",
            json!({
                "threadId": thread_id,
                "messageId": "",
                "kind": "error",
                "error": "Rebost couldn't finish that answer. Try again.",
            }),
        );
    }

    #[cfg(test)]
    fn cancel_count(&self) -> usize {
        crate::core::mutex_lock(&self.cancels).len()
    }

    #[cfg(test)]
    pub(crate) fn register_cancel_for_test(&self, message_id: &str) -> Arc<AtomicBool> {
        let flag = Arc::new(AtomicBool::new(false));
        crate::core::mutex_lock(&self.cancels).insert(message_id.to_string(), flag.clone());
        flag
    }

    /// Handle one user message end to end. Emits `rebost://chat` events and
    /// returns the finished assistant message.
    pub async fn send_message(
        self: &Arc<Self>,
        thread_id: &str,
        text: &str,
        shelf_id: Option<String>,
    ) -> Result<StoredMessage> {
        let ctx = &self.ctx;
        let now = chrono::Utc::now();
        let text = crate::limits::clip_chars(text, crate::limits::PROMPT_MAX_CHARS);

        // Persist + index the user message so later turns can search earlier chats.
        let user_message = StoredMessage {
            id: crate::ids::message_id(),
            role: "user".into(),
            text: text.clone(),
            thinking: None,
            activity: Vec::new(),
            ts: now.to_rfc3339(),
            shelf_id: shelf_id.clone(),
            sources: Vec::new(),
            status: "done".into(),
        };
        Conversations::append(&ctx.paths, thread_id, &user_message)?;
        let lang = guess_message_lang(&text);
        if let Err(error) =
            ctx.search
                .index_message(thread_id, &user_message.id, "user", &text, lang, now)
        {
            log::warn!("index user message: {error:#}");
        }

        let assistant_id = crate::ids::message_id();
        let activity_log = Mutex::new(Vec::<conversations::ActivityStep>::new());
        let emit = |kind: &str, payload: serde_json::Value| {
            if kind == "status" {
                if let Some(stage) = payload.get("stage").and_then(|v| v.as_str()) {
                    let file = payload
                        .get("file")
                        .and_then(|v| v.as_str())
                        .filter(|name| !name.is_empty())
                        .map(str::to_string);
                    if let Ok(mut log) = activity_log.lock() {
                        conversations::push_activity(&mut log, stage, file);
                    }
                }
            }
            let mut base = json!({
                "threadId": thread_id,
                "messageId": assistant_id,
                "kind": kind,
            });
            if let (Some(base_map), Some(extra)) = (base.as_object_mut(), payload.as_object()) {
                for (k, v) in extra {
                    base_map.insert(k.clone(), v.clone());
                }
            }
            ctx.events.emit("rebost://chat", base);
        };

        let cancel = Arc::new(AtomicBool::new(false));
        crate::core::mutex_lock(&self.cancels).insert(assistant_id.clone(), cancel.clone());

        emit("queued", json!({ "userMessageId": user_message.id }));

        // One answer at a time. The user message is already saved; this send
        // waits here if another conversation is still generating.
        let _generation = match self.generation.try_lock() {
            Ok(guard) => guard,
            Err(_) => {
                emit("status", json!({ "stage": "waiting" }));
                self.generation.lock().await
            }
        };

        let upload_owned =
            Conversations::get(&ctx.paths, thread_id).and_then(|t| t.upload_shelf_id);
        let (library_id, upload_id) = turn_shelf_ids(shelf_id.as_deref(), upload_owned.as_deref());
        let library_think = shelf_think_level(ctx, library_id);
        let upload_think = if upload_id.is_some() {
            ThinkLevel::Deep
        } else {
            ThinkLevel::Off
        };
        let think = library_think.max(upload_think);
        let focus_docs = focus::focus_upload_docs(ctx, upload_id, &text);
        let named_attachment = !focus_docs.is_empty();
        let prefer_coverage = named_attachment && focus::whole_document_intent(&text);
        let extra = extra_search_for_turn(
            &self.engine,
            ctx,
            &text,
            library_id,
            upload_id,
            think,
            named_attachment,
            prefer_coverage,
            &cancel,
            &emit,
        )
        .await;
        let mut prepared = if cancel.load(Ordering::Relaxed) {
            None
        } else {
            if should_emit_reading(library_id, upload_id) {
                emit("status", json!({ "stage": "reading" }));
            }
            Some(prepare_turn(
                ctx,
                thread_id,
                &text,
                library_id,
                upload_id,
                &user_message.id,
                &extra,
                library_think,
                &focus_docs,
            )?)
        };

        let started_emit = std::sync::Once::new();
        let result = match prepared.as_mut() {
            Some(turn) if !cancel.load(Ordering::Relaxed) => {
                generate_with_tools(
                    &self.engine,
                    ctx,
                    turn,
                    thread_id,
                    library_id,
                    upload_id,
                    think,
                    &cancel,
                    &emit,
                    &started_emit,
                )
                .await
            }
            _ => Ok(ChatOutput::default()),
        };
        crate::core::mutex_lock(&self.cancels).remove(&assistant_id);

        let (answer_text, thinking_text, status) = match result {
            Ok(output) => {
                let cancelled = cancel.load(Ordering::Relaxed);
                (
                    output.answer,
                    output.thinking,
                    if cancelled { "stopped" } else { "done" },
                )
            }
            Err(error) => {
                log::error!("generation failed: {error:#}");
                emit(
                    "error",
                    json!({ "error": "Rebost couldn't finish that answer. Try again." }),
                );
                (String::new(), String::new(), "error")
            }
        };

        // The model may cite only the source ids it received.
        let sources = prepared.map(|p| p.sources).unwrap_or_default();
        let valid_ids: Vec<String> = sources.iter().map(|s| s.sid.clone()).collect();
        let cleaned = sanitize_citations(&answer_text, &valid_ids);
        let cited: Vec<SourcePassage> = sources
            .into_iter()
            .filter(|s| cleaned.contains(&format!("[{}]", s.sid)))
            .collect();

        let activity = activity_log
            .lock()
            .map(|mut log| std::mem::take(&mut *log))
            .unwrap_or_default();
        let mut assistant_message = StoredMessage {
            id: assistant_id.clone(),
            role: "assistant".into(),
            text: cleaned,
            thinking: if thinking_text.is_empty() {
                None
            } else {
                Some(thinking_text)
            },
            activity,
            ts: chrono::Utc::now().to_rfc3339(),
            shelf_id: shelf_id.clone(),
            sources: cited,
            status: status.to_string(),
        };
        conversations::compact_message(&mut assistant_message);
        if status != "error" {
            Conversations::append(&ctx.paths, thread_id, &assistant_message)?;
            let lang = guess_message_lang(&assistant_message.text);
            if let Err(error) = ctx.search.index_message(
                thread_id,
                &assistant_message.id,
                "assistant",
                &assistant_message.text,
                lang,
                chrono::Utc::now(),
            ) {
                log::warn!("index assistant message: {error:#}");
            }
        }
        emit(
            "done",
            json!({ "message": assistant_message, "status": status }),
        );
        Ok(assistant_message)
    }
}

async fn generate_with_tools(
    engine: &Arc<Engine>,
    ctx: &Ctx,
    turn: &mut PreparedTurn,
    thread_id: &str,
    shelf_id: Option<&str>,
    upload_shelf_id: Option<&str>,
    think: ThinkLevel,
    cancel: &Arc<AtomicBool>,
    emit: impl Fn(&str, serde_json::Value),
    started_emit: &std::sync::Once,
) -> Result<ChatOutput> {
    emit("status", json!({ "stage": "thinking" }));
    let files = if turn.stuffed {
        Vec::new()
    } else {
        catalog_for_turn(ctx, shelf_id, upload_shelf_id)
    };
    let shelf_ok = !files.is_empty();
    let chats_ok = shelf_id
        .is_some_and(|shelf| Conversations::has_other_shelf_messages(&ctx.paths, thread_id, shelf));
    let mut used = tools::ToolUse::default();
    let mut collected = ChatOutput::default();
    let mut rounds = 0usize;
    let mut answer_only = false;
    let mut did_answer_retry = false;
    let prompt_len = turn.messages.len();
    let mut thinking = match think {
        ThinkLevel::Deep => ChatThinking::Deep,
        ThinkLevel::Off | ThinkLevel::Light => ChatThinking::Off,
    };

    loop {
        if cancel.load(Ordering::Relaxed) {
            break;
        }
        let paging = turn
            .sources
            .iter()
            .any(|s| focus::window_is_truncated(ctx, s));
        let named_or_upload =
            upload_shelf_id.is_some() || turn.sources.iter().any(focus::is_open_window);
        let max_rounds = focus::max_tool_rounds(think, named_or_upload, paging);
        let online = crate::core::read_lock(&ctx.settings).allow_online_research;
        let allowed =
            tools::ToolSet::new(shelf_ok, !turn.sources.is_empty(), online, chats_ok, &used);
        let offer_tools = !answer_only && rounds < max_rounds && allowed.any();
        let mut options = ChatOptions::stream(0.7, answer_token_budget(ctx));
        options.thinking = thinking;
        if offer_tools {
            options.tools = Some(allowed.schema(&tools::labels_for_schema(&files)));
            options.tool_choice = Some("auto".into());
        }

        // Hide tool dumps on the forced answer round too, so a leftover call
        // does not become the visible reply.
        let mut holdback = tools::AnswerHoldback::new(offer_tools || answer_only);
        let output = engine
            .complete(&turn.messages, options, cancel, |event| {
                started_emit.call_once(|| emit("started", json!({})));
                match event {
                    StreamEvent::Thinking(delta) => {
                        emit("thinking", json!({ "text": delta }));
                    }
                    StreamEvent::Answer(delta) => {
                        if let Some(flush) = holdback.push(delta) {
                            emit("delta", json!({ "text": flush }));
                        }
                    }
                    StreamEvent::PromoteAnswerToThinking => {
                        emit("promote", json!({}));
                    }
                }
            })
            .await?;

        if !output.thinking.is_empty() {
            if !collected.thinking.is_empty() {
                collected.thinking.push('\n');
            }
            collected.thinking.push_str(&output.thinking);
        }

        let hidden = holdback.take_hidden();
        if cancel.load(Ordering::Relaxed) {
            collected.answer = holdback.visible_answer(&hidden, &output.answer);
            collected.finish_reason = output.finish_reason;
            break;
        }

        let calls = if offer_tools {
            let mut calls = tools::merge_tool_calls(output.tool_calls.clone(), &output.answer);
            if calls.is_empty() && !hidden.is_empty() {
                calls = tools::parse_tool_calls_from_text(&hidden);
            }
            calls
        } else {
            Vec::new()
        };

        if !calls.is_empty() && rounds < max_rounds && !answer_only {
            turn.messages.push(tools::assistant_tool_message(&calls));
            for call in &calls {
                if cancel.load(Ordering::Relaxed) {
                    break;
                }
                let hint = tools::status_hint(call, &turn.sources);
                emit_tool_status(&emit, &hint);
                let online = crate::core::read_lock(&ctx.settings).allow_online_research;
                let outcome = tools::run_tool(
                    call,
                    &tools::ToolCtx {
                        ctx,
                        thread_id,
                        shelf_id,
                        upload_shelf_id,
                        files: &files,
                        sources: &turn.sources,
                        cited: &turn.cited,
                        budget: turn.budget,
                        think,
                        allowed: tools::ToolSet::new(
                            shelf_ok,
                            !turn.sources.is_empty(),
                            online,
                            chats_ok,
                            &used,
                        ),
                        cancel: cancel.as_ref(),
                        open_next: used.open_next.clone(),
                    },
                )
                .await;
                if let Some(file) = outcome.file.as_deref() {
                    if hint.file.as_deref() != Some(file) {
                        emit_tool_status(
                            &emit,
                            &tools::StatusHint {
                                stage: hint.stage,
                                file: Some(file.to_string()),
                            },
                        );
                    }
                }
                tools::note_use(&mut used, call, &outcome.change);
                tools::apply_change(&mut turn.sources, outcome.change);
                turn.messages
                    .push(tools::tool_result_message(call, outcome.message));
            }
            if cancel.load(Ordering::Relaxed) {
                collected.answer = holdback.visible_answer(&hidden, &output.answer);
                collected.finish_reason = output.finish_reason;
                break;
            }
            rounds += 1;
            let after = tools::ToolSet::new(
                shelf_ok,
                !turn.sources.is_empty(),
                crate::core::read_lock(&ctx.settings).allow_online_research,
                chats_ok,
                &used,
            );
            if !after.follow_up_useful() {
                answer_only = true;
                emit("status", json!({ "stage": "thinking" }));
            }
            continue;
        }

        let answer = holdback.visible_answer(&hidden, &output.answer);
        if !holdback.released() && !answer.is_empty() {
            started_emit.call_once(|| emit("started", json!({})));
            emit("delta", json!({ "text": answer }));
        }
        if answer.is_empty() && !did_answer_retry {
            did_answer_retry = true;
            answer_only = true;
            thinking = ChatThinking::Off;
            if should_drop_tool_transcript(rounds) {
                rewind_to_prompt(&mut turn.messages, prompt_len);
                log::info!("empty follow-up after tools; answering without tool notes");
            }
            emit("status", json!({ "stage": "thinking" }));
            continue;
        }
        collected.answer = answer;
        collected.finish_reason = output.finish_reason;
        break;
    }
    if should_fail_empty_answer(&collected.answer, cancel.load(Ordering::Relaxed)) {
        return Err(anyhow!("empty generation"));
    }
    Ok(collected)
}

fn should_fail_empty_answer(answer: &str, cancelled: bool) -> bool {
    !cancelled && answer.trim().is_empty()
}

/// A blank follow-up after `search_chats` (or any tool) stays blank if we
/// keep the tool transcript: leftover calls and think-only output are
/// withheld. Drop those notes and answer from the original prompt.
fn should_drop_tool_transcript(tool_rounds: usize) -> bool {
    tool_rounds > 0
}

fn rewind_to_prompt(messages: &mut Vec<ChatMessage>, prompt_len: usize) {
    messages.truncate(prompt_len);
}

fn should_emit_reading(library_id: Option<&str>, upload_id: Option<&str>) -> bool {
    library_id.is_some() || upload_id.is_some()
}

fn emit_tool_status(emit: &impl Fn(&str, serde_json::Value), hint: &tools::StatusHint) {
    match &hint.file {
        Some(file) if !file.is_empty() => {
            emit("status", json!({ "stage": hint.stage, "file": file }));
        }
        _ => emit("status", json!({ "stage": hint.stage })),
    }
}

/// Delete a conversation and any hidden upload Shelf tied to it.
pub fn delete_thread(ctx: &Arc<Ctx>, thread_id: &str) -> Result<()> {
    let meta = Conversations::get(&ctx.paths, thread_id);
    Conversations::delete(&ctx.paths, thread_id)?;
    if let Err(error) = ctx.search.remove_thread(thread_id) {
        log::warn!("remove thread from index: {error:#}");
    }
    let shelf_id = meta
        .as_ref()
        .and_then(|t| t.upload_shelf_id.clone())
        .or_else(|| {
            crate::core::read_lock(&ctx.library)
                .conversation_shelf(thread_id)
                .map(|s| s.id.clone())
        });
    if let Some(shelf_id) = shelf_id {
        ctx.ingest_queue.cancel_shelf(&shelf_id);
        let doc_ids = {
            let mut library = crate::core::write_lock(&ctx.library);
            library.remove_shelf(&ctx.paths, &shelf_id)?
        };
        if let Err(error) = ctx.search.remove_shelf(&shelf_id) {
            log::warn!("remove conversation shelf from index: {error:#}");
        }
        crate::ingest::remove_documents(ctx, &shelf_id, &doc_ids);
    }
    Ok(())
}

struct PreparedTurn {
    messages: Vec<ChatMessage>,
    sources: Vec<SourcePassage>,
    stuffed: bool,
    budget: usize,
    cited: Vec<SourcePassage>,
}

fn turn_shelf_ids<'a>(
    shelf_id: Option<&'a str>,
    upload_shelf_id: Option<&'a str>,
) -> (Option<&'a str>, Option<&'a str>) {
    let library = shelf_id.filter(|id| Some(*id) != upload_shelf_id);
    (library, upload_shelf_id)
}

fn catalog_for_turn(
    ctx: &Ctx,
    library_id: Option<&str>,
    upload_id: Option<&str>,
) -> Vec<tools::ShelfFile> {
    let mut files = Vec::new();
    if let Some(id) = library_id {
        files.extend(tools::catalog(ctx, id));
    }
    if let Some(id) = upload_id {
        if Some(id) != library_id {
            files.extend(tools::catalog(ctx, id));
        }
    }
    files
}

struct Retrieved {
    passages: Vec<SourcePassage>,
    stuffed: bool,
}

impl Retrieved {
    fn empty() -> Self {
        Self {
            passages: Vec::new(),
            stuffed: true,
        }
    }
}

struct RetrieveOpts<'a> {
    extra_queries: &'a [String],
    think: ThinkLevel,
    budget: usize,
    focus_doc_ids: &'a [String],
    prefer_coverage: bool,
    attachment: bool,
}

fn retrieve_from_shelf(
    ctx: &Ctx,
    shelf_id: &str,
    text: &str,
    opts: RetrieveOpts<'_>,
) -> Result<Retrieved> {
    let plan = retrieve_plan(opts.think);
    if let Some(full) = try_stuff_shelf_docs(ctx, shelf_id, opts.budget) {
        return Ok(Retrieved {
            passages: full,
            stuffed: true,
        });
    }
    if opts.prefer_coverage && !opts.focus_doc_ids.is_empty() {
        let mut passages = Vec::new();
        let share = (opts.budget / opts.focus_doc_ids.len()).max(256);
        for id in opts.focus_doc_ids {
            passages.extend(focus::coverage_passages(ctx, shelf_id, id, share));
        }
        if !passages.is_empty() {
            if plan.expand_top > 0 {
                passages = expand_top_files(
                    ctx,
                    shelf_id,
                    passages,
                    opts.budget,
                    plan.expand_top,
                    opts.focus_doc_ids,
                );
            }
            return Ok(Retrieved {
                passages,
                stuffed: false,
            });
        }
    }
    let relaxed = crate::core::read_lock(&ctx.library)
        .shelf(shelf_id)
        .is_some_and(|s| s.thread_id.is_some());
    let files = focus::shelf_ready_files(ctx, shelf_id);
    let preserve_order = !opts.extra_queries.is_empty();
    let (hits, named) = if opts.extra_queries.is_empty() {
        ctx.search
            .search_and_merge_named(text, shelf_id, &files, plan.search_limit)?
    } else {
        let mut queries = Vec::with_capacity(1 + opts.extra_queries.len());
        queries.push(text.to_string());
        queries.extend(opts.extra_queries.iter().cloned());
        ctx.search
            .search_fused(&queries, shelf_id, &files, plan.search_limit)?
    };
    let mut named = named;
    for id in opts.focus_doc_ids {
        if !named.iter().any(|n| n == id) {
            named.push(id.clone());
        }
    }
    let mut overlap_tokens = ctx.search.query_tokens(text);
    for extra in opts.extra_queries {
        overlap_tokens.extend(ctx.search.query_tokens(extra));
    }
    let caps = if opts.attachment {
        focus::attachment_caps(opts.think)
    } else {
        plan.caps
    };
    let mut gated = if relaxed || opts.attachment {
        gate::gate_passages(hits, &[], &named, caps, preserve_order)
    } else {
        gate::gate_passages(hits, &overlap_tokens, &named, caps, preserve_order)
    };
    gated = neighbors::widen_neighbor_passages(ctx, shelf_id, gated, plan.neighbor_radius);
    if plan.expand_top > 0 && (!relaxed || opts.attachment) {
        gated = expand_top_files(
            ctx,
            shelf_id,
            gated,
            opts.budget,
            plan.expand_top,
            opts.focus_doc_ids,
        );
    }
    Ok(Retrieved {
        passages: gated,
        stuffed: false,
    })
}

fn prepare_turn(
    ctx: &Ctx,
    thread_id: &str,
    text: &str,
    shelf_id: Option<&str>,
    upload_shelf_id: Option<&str>,
    user_message_id: &str,
    extra_queries: &[String],
    library_think: ThinkLevel,
    focus_docs: &[String],
) -> Result<PreparedTurn> {
    let requested = ctx.context_budget();
    let budget = retrieval_budget(ctx, requested);
    let (library_id, upload_id) = turn_shelf_ids(shelf_id, upload_shelf_id);
    let named_attachment = !focus_docs.is_empty();
    let prefer_coverage = named_attachment && focus::whole_document_intent(text);
    let upload_budget = focus::upload_budget_chars(
        budget,
        upload_id.is_some(),
        named_attachment,
        prefer_coverage,
    );
    let history = Conversations::recent_history(
        &ctx.paths,
        thread_id,
        HISTORY_MAX_MESSAGES,
        HISTORY_MAX_CHARS,
    );
    let cited = cited_sources(&history);
    let extra_queries = if named_attachment {
        extra_queries.to_vec()
    } else {
        merge_search_queries(
            prior_search_queries(&history, user_message_id, text),
            extra_queries,
        )
    };
    let extra_queries = extra_queries.as_slice();
    let library_focus = match library_id {
        Some(id) if !named_attachment => last_cited_document_ids(&history, id),
        _ => Vec::new(),
    };

    let upload = match upload_id {
        Some(id) if upload_budget >= 64 => retrieve_from_shelf(
            ctx,
            id,
            text,
            RetrieveOpts {
                extra_queries,
                think: ThinkLevel::Deep,
                budget: upload_budget,
                focus_doc_ids: focus_docs,
                prefer_coverage,
                attachment: true,
            },
        )?,
        Some(_) => Retrieved {
            passages: Vec::new(),
            stuffed: false,
        },
        None => Retrieved::empty(),
    };
    let upload_sources = gate::take_passages(upload.passages, upload_budget);
    let remaining = budget.saturating_sub(tools::sources_cost(&upload_sources));
    let library_extras = if named_attachment {
        &[][..]
    } else {
        extra_queries
    };
    let library = match library_id {
        Some(id) if remaining >= 64 => retrieve_from_shelf(
            ctx,
            id,
            text,
            RetrieveOpts {
                extra_queries: library_extras,
                think: library_think,
                budget: remaining,
                focus_doc_ids: &library_focus,
                prefer_coverage: false,
                attachment: false,
            },
        )?,
        Some(_) => Retrieved {
            passages: Vec::new(),
            stuffed: false,
        },
        None => Retrieved::empty(),
    };
    let library_sources = gate::take_passages(library.passages, remaining);
    let stuffed = library.stuffed && upload.stuffed;
    let mut sources = upload_sources;
    sources.extend(library_sources);
    tools::assign_sids(&mut sources, &cited);

    let (shelf_name, shelf_inventory) = shelf_prompt_bits(ctx, library_id, upload_id);
    let mut named_files = Vec::new();
    if let Some(id) = upload_id {
        named_files.extend(focus::named_files_on_shelf(ctx, id, text));
        if named_files.is_empty() {
            for doc_id in focus_docs {
                if let Some(meta) = crate::core::read_lock(&ctx.library).document(id, doc_id) {
                    named_files.push((id.to_string(), doc_id.clone(), meta.file_name));
                }
            }
        }
    }
    if let Some(id) = library_id {
        named_files.extend(focus::named_files_on_shelf(ctx, id, text));
        for doc_id in &library_focus {
            if named_files
                .iter()
                .any(|(_, existing, _)| existing == doc_id)
            {
                continue;
            }
            if let Some(meta) = crate::core::read_lock(&ctx.library).document(id, doc_id) {
                named_files.push((id.to_string(), doc_id.clone(), meta.file_name));
            }
        }
    }
    let named_notes = focus::format_named_file_notes(ctx, &named_files);
    let settings = crate::core::read_lock(&ctx.settings);
    let house_rules =
        crate::limits::clip_chars(&settings.house_rules, crate::limits::HOUSE_RULES_MAX_CHARS);
    let online = settings.allow_online_research;
    drop(settings);
    let avatar_name = Conversations::get(&ctx.paths, thread_id)
        .and_then(|thread| avatars::name_for(&thread.avatar_id).map(str::to_string))
        .unwrap_or_else(|| "Rebost".into());
    let system = build_system_prompt(
        &house_rules,
        shelf_name.as_deref(),
        shelf_inventory.as_deref(),
        named_notes.as_deref(),
        stuffed,
        (library_id.is_some() || upload_id.is_some()) && !stuffed,
        online,
        &avatar_name,
    );

    let mut messages = vec![ChatMessage::text("system", system)];
    for previous in &history {
        if previous.id == user_message_id {
            continue;
        }
        messages.push(ChatMessage::text(
            previous.role.clone(),
            history_message_text(previous),
        ));
    }
    messages.push(ChatMessage::text("user", text));
    let retrieved = format_retrieved_context(&sources);
    if !retrieved.is_empty() {
        let call = retrieval_call(text);
        messages.push(tools::assistant_tool_message(std::slice::from_ref(&call)));
        messages.push(tools::tool_result_message(&call, retrieved));
    }
    Ok(PreparedTurn {
        messages,
        sources,
        stuffed,
        budget,
        cited,
    })
}

/// Retrieved passages arrive as a `search_shelf` result rather than a second
/// system message. Qwen and other templates raise `System message must be at
/// the beginning` for a system turn anywhere but index 0, and a tool result
/// still reads as something Rebost fetched rather than something the user
/// pasted.
fn retrieval_call(query: &str) -> ToolCall {
    const QUERY_MAX_CHARS: usize = 300;
    ToolCall::function(
        "rebost_retrieval",
        tools::SEARCH_SHELF,
        json!({ "query": crate::limits::clip_chars(query, QUERY_MAX_CHARS) }).to_string(),
    )
}

fn history_message_text(message: &StoredMessage) -> String {
    let mut text = gate::truncate_at_boundary(&message.text, HISTORY_MESSAGE_MAX_CHARS);
    if message.role == "user" {
        return text;
    }
    let legend = format_citation_legend(&message.sources);
    if legend.is_empty() {
        return text;
    }
    if !text.is_empty() {
        text.push_str("\n\n");
    }
    text.push_str(&legend);
    text
}

fn prior_search_queries(
    history: &[StoredMessage],
    current_id: &str,
    current_text: &str,
) -> Vec<String> {
    let current_fold = fold_ws(current_text);
    let users: Vec<&str> = history
        .iter()
        .filter(|message| message.role == "user" && message.id != current_id)
        .map(|message| message.text.trim())
        .filter(|text| text.chars().count() >= 3 && fold_ws(text) != current_fold)
        .collect();
    users
        .into_iter()
        .rev()
        .take(2)
        .collect::<Vec<_>>()
        .into_iter()
        .rev()
        .map(str::to_string)
        .collect()
}

fn merge_search_queries(mut prior: Vec<String>, extra: &[String]) -> Vec<String> {
    for query in extra {
        let fold = fold_ws(query);
        if prior.iter().any(|existing| fold_ws(existing) == fold) {
            continue;
        }
        prior.push(query.clone());
    }
    prior
}

fn cited_sources(history: &[StoredMessage]) -> Vec<SourcePassage> {
    history
        .iter()
        .filter(|message| message.role != "user")
        .flat_map(|message| message.sources.iter().cloned())
        .collect()
}

fn last_cited_document_ids(history: &[StoredMessage], shelf_id: &str) -> Vec<String> {
    let Some(message) = history
        .iter()
        .rev()
        .find(|message| message.role != "user" && !message.sources.is_empty())
    else {
        return Vec::new();
    };
    let mut ids = Vec::new();
    for source in &message.sources {
        if source.shelf_id == shelf_id
            && !source.document_id.is_empty()
            && !ids.contains(&source.document_id)
        {
            ids.push(source.document_id.clone());
        }
    }
    ids
}

fn chat_spawn_plan(ctx: &Ctx) -> Option<crate::engine::tune::SpawnPlan> {
    let profile = crate::engine::catalog::MachineProfile::detect(ctx.paths.base());
    let pin = crate::engine::preferred_engine_pin().ok()?;
    let hint = crate::core::read_lock(&ctx.settings)
        .active_model
        .as_ref()
        .map(|model| crate::engine::tune::ModelHint::from_active(model, &ctx.paths.models_dir()));
    Some(match hint.as_ref() {
        Some(model) => crate::engine::tune::SpawnPlan::for_model(&profile, pin, Some(model)),
        None => crate::engine::tune::SpawnPlan::from_profile(&profile, pin),
    })
}

fn answer_token_budget(ctx: &Ctx) -> u32 {
    chat_spawn_plan(ctx)
        .map(|plan| plan.answer_tokens)
        .unwrap_or_else(|| crate::engine::tune::max_answer_tokens(4096))
}

fn retrieval_budget(ctx: &Ctx, requested: usize) -> usize {
    match chat_spawn_plan(ctx) {
        Some(plan) => crate::engine::tune::retrieval_char_budget_with(
            plan.context_tokens,
            plan.answer_tokens,
            requested,
        ),
        None => requested,
    }
}

fn stuffed_file_cost(title: &str, bytes: u64) -> usize {
    (bytes as usize)
        .saturating_add(title.len())
        .saturating_add(64)
}

pub(super) struct RetrievePlan {
    pub search_limit: usize,
    pub expand_top: usize,
    pub extra_queries: usize,
    pub neighbor_radius: usize,
    pub caps: gate::GateCaps,
}

pub(super) fn retrieve_plan(level: ThinkLevel) -> RetrievePlan {
    match level {
        ThinkLevel::Off => RetrievePlan {
            search_limit: 24,
            expand_top: 0,
            extra_queries: 0,
            neighbor_radius: neighbors::OFF_RADIUS_CHARS,
            caps: gate::GateCaps::default(),
        },
        ThinkLevel::Light => RetrievePlan {
            search_limit: 24,
            expand_top: 0,
            extra_queries: 3,
            neighbor_radius: neighbors::LIGHT_RADIUS_CHARS,
            caps: gate::GateCaps {
                relative_floor: 0.15,
                ..gate::GateCaps::default()
            },
        },
        ThinkLevel::Deep => RetrievePlan {
            search_limit: 32,
            expand_top: 2,
            extra_queries: 3,
            neighbor_radius: neighbors::DEEP_RADIUS_CHARS,
            caps: gate::GateCaps {
                max_passages: 12,
                max_per_doc: 4,
                max_per_named: 8,
                relative_floor: 0.12,
            },
        },
    }
}

fn shelf_think_level(ctx: &Ctx, shelf_id: Option<&str>) -> ThinkLevel {
    let Some(id) = shelf_id else {
        return ThinkLevel::Off;
    };
    crate::core::read_lock(&ctx.library)
        .shelf(id)
        .map(|s| s.think_level)
        .unwrap_or_default()
}

async fn extra_search_for_turn(
    engine: &Arc<Engine>,
    ctx: &Ctx,
    text: &str,
    library_id: Option<&str>,
    upload_id: Option<&str>,
    think: ThinkLevel,
    named_attachment: bool,
    prefer_coverage: bool,
    cancel: &Arc<AtomicBool>,
    emit: impl Fn(&str, serde_json::Value),
) -> Vec<String> {
    let count = retrieve_plan(think).extra_queries;
    if count == 0 || cancel.load(Ordering::Relaxed) {
        return Vec::new();
    }
    let budget = retrieval_budget(ctx, ctx.context_budget());
    let upload_needs = upload_id.is_some_and(|id| {
        !prefer_coverage && matches!(stuff_plan(ctx, id, budget), StuffPlan::Search)
    });
    let library_needs = library_id.is_some_and(|id| {
        !named_attachment && matches!(stuff_plan(ctx, id, budget), StuffPlan::Search)
    });
    if !upload_needs && !library_needs {
        return Vec::new();
    }
    emit("status", json!({ "stage": "looking" }));
    extra_search_queries(engine, text, count, cancel).await
}

fn expand_top_files(
    ctx: &Ctx,
    shelf_id: &str,
    passages: Vec<SourcePassage>,
    budget: usize,
    top_n: usize,
    focus_doc_ids: &[String],
) -> Vec<SourcePassage> {
    if top_n == 0 || passages.is_empty() {
        return passages;
    }
    let mut ranked_ids: Vec<String> = Vec::new();
    for id in focus_doc_ids {
        if !ranked_ids.iter().any(|existing| existing == id) {
            ranked_ids.push(id.clone());
        }
        if ranked_ids.len() >= top_n {
            break;
        }
    }
    for passage in &passages {
        if !ranked_ids.iter().any(|id| id == &passage.document_id) {
            ranked_ids.push(passage.document_id.clone());
        }
        if ranked_ids.len() >= top_n {
            break;
        }
    }
    let mut expanded = Vec::new();
    let mut used = 0usize;
    let mut replaced: HashSet<String> = HashSet::new();
    for id in &ranked_ids {
        let Some(meta) = crate::core::read_lock(&ctx.library).document(shelf_id, id) else {
            continue;
        };
        let path = ctx.paths.extracted_path(shelf_id, id);
        let Ok(info) = std::fs::metadata(&path) else {
            continue;
        };
        let cost = stuffed_file_cost(&meta.file_name, info.len());
        if used + cost > budget {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue;
        };
        used += cost;
        replaced.insert(id.clone());
        let score = passages
            .iter()
            .filter(|p| &p.document_id == id)
            .map(|p| p.score)
            .fold(0.0f32, f32::max);
        expanded.push(SourcePassage {
            sid: String::new(),
            document_id: id.clone(),
            shelf_id: shelf_id.to_string(),
            title: meta.file_name,
            section: None,
            page_start: None,
            page_end: meta.pages,
            body: text,
            path: meta.path,
            score,
        });
    }
    for passage in passages {
        if replaced.contains(&passage.document_id) {
            continue;
        }
        expanded.push(passage);
    }
    expanded.sort_by(|a, b| b.score.total_cmp(&a.score));
    expanded
}

/// Send the whole extracted file when it fits the remaining window.
///
/// Local AIs here run at 4k–8k context. Prefill is the slow part: the install
/// benchmark sizes this budget so prompt processing stays around two seconds,
/// then the spawn plan caps it so the prompt plus the answer still fit in `-c`.
/// When the files are smaller than that, stuffing beats search (no missed
/// passage). Longer files go through Tantivy.
fn try_stuff_shelf_docs(ctx: &Ctx, shelf_id: &str, budget: usize) -> Option<Vec<SourcePassage>> {
    let StuffPlan::Fits(planned) = stuff_plan(ctx, shelf_id, budget) else {
        return None;
    };
    let mut sources = Vec::with_capacity(planned.len());
    for (doc, path) in planned {
        let text = std::fs::read_to_string(&path).ok()?;
        sources.push(SourcePassage {
            sid: String::new(),
            document_id: doc.id.clone(),
            shelf_id: shelf_id.to_string(),
            title: doc.file_name.clone(),
            section: None,
            page_start: None,
            page_end: doc.pages,
            body: text,
            path: doc.path.clone(),
            score: 1.0,
        });
    }
    Some(sources)
}

enum StuffPlan {
    Empty,
    Fits(Vec<(DocumentMeta, PathBuf)>),
    Search,
}

/// Ready extracted files that fit `budget`, or why they cannot be sent whole.
fn stuff_plan(ctx: &Ctx, shelf_id: &str, budget: usize) -> StuffPlan {
    let docs = {
        let library = crate::core::read_lock(&ctx.library);
        library
            .documents(shelf_id)
            .into_iter()
            .filter(|d| d.status == DocStatus::Ready)
            .collect::<Vec<_>>()
    };
    if docs.is_empty() {
        return StuffPlan::Empty;
    }
    let mut planned = Vec::with_capacity(docs.len());
    let mut used = 0usize;
    for doc in docs {
        let path = ctx.paths.extracted_path(shelf_id, &doc.id);
        let Ok(info) = std::fs::metadata(&path) else {
            return StuffPlan::Search;
        };
        used = used.saturating_add(stuffed_file_cost(&doc.file_name, info.len()));
        if used > budget {
            return StuffPlan::Search;
        }
        planned.push((doc, path));
    }
    StuffPlan::Fits(planned)
}

fn shelf_inventory(ctx: &Ctx, shelf_id: &str) -> Option<(String, String)> {
    let library = crate::core::read_lock(&ctx.library);
    let name = library.shelf(shelf_id)?.name.clone();
    let docs = library.documents(shelf_id);
    let labels = shelf_file_labels(
        docs.iter()
            .map(|d| (d.file_name.as_str(), d.rel_path.as_str())),
    );
    let inventory = format_shelf_inventory(&name, &labels);
    Some((name, inventory))
}

fn shelf_prompt_bits(
    ctx: &Ctx,
    library_id: Option<&str>,
    upload_id: Option<&str>,
) -> (Option<String>, Option<String>) {
    let library = library_id.and_then(|id| shelf_inventory(ctx, id));
    let upload = upload_id.and_then(|id| shelf_inventory(ctx, id));
    match (library, upload) {
        (None, None) => (None, None),
        (Some((name, inventory)), None) | (None, Some((name, inventory))) => {
            (Some(name), Some(inventory))
        }
        (Some((name, library_inv)), Some((_, upload_inv))) => {
            (Some(name), Some(format!("{library_inv}\n{upload_inv}")))
        }
    }
}

#[cfg(test)]
mod cancel_tests;
#[cfg(test)]
mod prepare_tests;
