//! Chat orchestration. Every user message follows the same pipeline:
//!
//! ```text
//! user message
//!   → attached / named files first (Deep), then the selected Shelf
//!     whole extracted files when they fit the local-context budget,
//!     otherwise search; hits include nearby text
//!     Light / Deep: extra search queries fused in
//!     Deep: more of each top matching file when they fit;
//!          cheapest native model thinking when the template supports it
//!   → Retrieval Gate
//!   → local AI (house rules · shelf file index · original message · recent context · gated sources)
//!     The AI may search the Shelf again, read more around a citation,
//!     open a named file (one window at a time), or search earlier conversations
//!   → streamed answer with citations
//! ```
//!
//! Every answer is generated by the local model; search only supplies
//! source material when the files are too long to send whole.

mod avatars;
pub mod conversations;
mod focus;
mod neighbors;
mod prompts;
mod queries;
mod tools;

use anyhow::{anyhow, Result};
use serde_json::json;
use std::collections::{HashMap, HashSet};
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};

use crate::core::Ctx;
use crate::engine::{ChatMessage, ChatOptions, ChatOutput, ChatThinking, Engine, StreamEvent};
use crate::search::gate;
use crate::shelf::ThinkLevel;
use crate::types::{DocStatus, DocumentMeta, SourcePassage};
use conversations::{Conversations, StoredMessage};
pub use prompts::guess_message_lang;
use prompts::{
    build_system_prompt, build_user_content, format_shelf_inventory, sanitize_citations,
    shelf_file_labels,
};
use queries::extra_search_queries;

const HISTORY_MAX_MESSAGES: usize = 12;
const HISTORY_MAX_CHARS: usize = 6_000;
const HISTORY_MESSAGE_MAX_CHARS: usize = 4_000;

/// Local chat pipeline: retrieve, prompt, stream, and persist.
pub struct ChatService {
    ctx: Arc<Ctx>,
    engine: Arc<Engine>,
    cancels: Mutex<HashMap<String, Arc<AtomicBool>>>,
    /// One in-flight generation for the whole app. A second send waits here.
    generation: tokio::sync::Mutex<()>,
}

impl ChatService {
    pub fn new(ctx: Arc<Ctx>, engine: Arc<Engine>) -> Arc<Self> {
        Arc::new(Self {
            ctx,
            engine,
            cancels: Mutex::new(HashMap::new()),
            generation: tokio::sync::Mutex::new(()),
        })
    }

    pub fn cancel(&self, message_id: &str) {
        if let Some(flag) = crate::core::mutex_lock(&self.cancels).get(message_id) {
            flag.store(true, Ordering::Relaxed);
        }
    }

    /// Unlock the UI when `send_message` returns before it could emit `done`.
    pub(crate) fn notify_send_failed(&self, thread_id: &str) {
        self.ctx.events.emit(
            "rebost://chat",
            json!({
                "threadId": thread_id,
                "messageId": "",
                "kind": "error",
                "error": "Rebost couldn't finish that answer. Try again.",
            }),
        );
    }

    #[cfg(test)]
    fn cancel_count(&self) -> usize {
        crate::core::mutex_lock(&self.cancels).len()
    }

    #[cfg(test)]
    pub(crate) fn register_cancel_for_test(&self, message_id: &str) -> Arc<AtomicBool> {
        let flag = Arc::new(AtomicBool::new(false));
        crate::core::mutex_lock(&self.cancels).insert(message_id.to_string(), flag.clone());
        flag
    }

    /// Handle one user message end to end. Emits `rebost://chat` events and
    /// returns the finished assistant message.
    pub async fn send_message(
        self: &Arc<Self>,
        thread_id: &str,
        text: &str,
        shelf_id: Option<String>,
    ) -> Result<StoredMessage> {
        let ctx = &self.ctx;
        let now = chrono::Utc::now();
        let text = crate::limits::clip_chars(text, crate::limits::PROMPT_MAX_CHARS);

        // Persist + index the user message so later turns can search earlier chats.
        let user_message = StoredMessage {
            id: crate::ids::message_id(),
            role: "user".into(),
            text: text.clone(),
            thinking: None,
            activity: Vec::new(),
            ts: now.to_rfc3339(),
            shelf_id: shelf_id.clone(),
            sources: Vec::new(),
            status: "done".into(),
        };
        Conversations::append(&ctx.paths, thread_id, &user_message)?;
        let lang = guess_message_lang(&text);
        if let Err(error) =
            ctx.search
                .index_message(thread_id, &user_message.id, "user", &text, lang, now)
        {
            log::warn!("index user message: {error:#}");
        }

        let assistant_id = crate::ids::message_id();
        let activity_log = Mutex::new(Vec::<conversations::ActivityStep>::new());
        let emit = |kind: &str, payload: serde_json::Value| {
            if kind == "status" {
                if let Some(stage) = payload.get("stage").and_then(|v| v.as_str()) {
                    let file = payload
                        .get("file")
                        .and_then(|v| v.as_str())
                        .filter(|name| !name.is_empty())
                        .map(str::to_string);
                    if let Ok(mut log) = activity_log.lock() {
                        conversations::push_activity(&mut log, stage, file);
                    }
                }
            }
            let mut base = json!({
                "threadId": thread_id,
                "messageId": assistant_id,
                "kind": kind,
            });
            if let (Some(base_map), Some(extra)) = (base.as_object_mut(), payload.as_object()) {
                for (k, v) in extra {
                    base_map.insert(k.clone(), v.clone());
                }
            }
            ctx.events.emit("rebost://chat", base);
        };

        let cancel = Arc::new(AtomicBool::new(false));
        crate::core::mutex_lock(&self.cancels).insert(assistant_id.clone(), cancel.clone());

        emit("queued", json!({ "userMessageId": user_message.id }));

        // One answer at a time. The user message is already saved; this send
        // waits here if another conversation is still generating.
        let _generation = match self.generation.try_lock() {
            Ok(guard) => guard,
            Err(_) => {
                emit("status", json!({ "stage": "waiting" }));
                self.generation.lock().await
            }
        };

        let upload_owned =
            Conversations::get(&ctx.paths, thread_id).and_then(|t| t.upload_shelf_id);
        let (library_id, upload_id) = turn_shelf_ids(shelf_id.as_deref(), upload_owned.as_deref());
        let library_think = shelf_think_level(ctx, library_id);
        let upload_think = if upload_id.is_some() {
            ThinkLevel::Deep
        } else {
            ThinkLevel::Off
        };
        let think = library_think.max(upload_think);
        let focus_docs = focus::focus_upload_docs(ctx, upload_id, &text);
        let named_attachment = !focus_docs.is_empty();
        let prefer_coverage = named_attachment && focus::whole_document_intent(&text);
        let extra = extra_search_for_turn(
            &self.engine,
            ctx,
            &text,
            library_id,
            upload_id,
            think,
            named_attachment,
            prefer_coverage,
            &cancel,
            &emit,
        )
        .await;
        let mut prepared = if cancel.load(Ordering::Relaxed) {
            None
        } else {
            if should_emit_reading(library_id, upload_id) {
                emit("status", json!({ "stage": "reading" }));
            }
            Some(prepare_turn(
                ctx,
                thread_id,
                &text,
                library_id,
                upload_id,
                &user_message.id,
                &extra,
                library_think,
                &focus_docs,
            )?)
        };

        let started_emit = std::sync::Once::new();
        let result = match prepared.as_mut() {
            Some(turn) if !cancel.load(Ordering::Relaxed) => {
                generate_with_tools(
                    &self.engine,
                    ctx,
                    turn,
                    thread_id,
                    library_id,
                    upload_id,
                    think,
                    &cancel,
                    &emit,
                    &started_emit,
                )
                .await
            }
            _ => Ok(ChatOutput::default()),
        };
        crate::core::mutex_lock(&self.cancels).remove(&assistant_id);

        let (answer_text, thinking_text, status) = match result {
            Ok(output) => {
                let cancelled = cancel.load(Ordering::Relaxed);
                (
                    output.answer,
                    output.thinking,
                    if cancelled { "stopped" } else { "done" },
                )
            }
            Err(error) => {
                log::error!("generation failed: {error:#}");
                emit(
                    "error",
                    json!({ "error": "Rebost couldn't finish that answer. Try again." }),
                );
                (String::new(), String::new(), "error")
            }
        };

        // The model may cite only the source ids it received.
        let sources = prepared.map(|p| p.sources).unwrap_or_default();
        let valid_ids: Vec<String> = sources.iter().map(|s| s.sid.clone()).collect();
        let cleaned = sanitize_citations(&answer_text, &valid_ids);
        let cited: Vec<SourcePassage> = sources
            .into_iter()
            .filter(|s| cleaned.contains(&format!("[{}]", s.sid)))
            .collect();

        let activity = activity_log
            .lock()
            .map(|mut log| std::mem::take(&mut *log))
            .unwrap_or_default();
        let mut assistant_message = StoredMessage {
            id: assistant_id.clone(),
            role: "assistant".into(),
            text: cleaned,
            thinking: if thinking_text.is_empty() {
                None
            } else {
                Some(thinking_text)
            },
            activity,
            ts: chrono::Utc::now().to_rfc3339(),
            shelf_id: shelf_id.clone(),
            sources: cited,
            status: status.to_string(),
        };
        conversations::compact_message(&mut assistant_message);
        if status != "error" {
            Conversations::append(&ctx.paths, thread_id, &assistant_message)?;
            let lang = guess_message_lang(&assistant_message.text);
            if let Err(error) = ctx.search.index_message(
                thread_id,
                &assistant_message.id,
                "assistant",
                &assistant_message.text,
                lang,
                chrono::Utc::now(),
            ) {
                log::warn!("index assistant message: {error:#}");
            }
        }
        emit(
            "done",
            json!({ "message": assistant_message, "status": status }),
        );
        Ok(assistant_message)
    }
}

async fn generate_with_tools(
    engine: &Arc<Engine>,
    ctx: &Ctx,
    turn: &mut PreparedTurn,
    thread_id: &str,
    shelf_id: Option<&str>,
    upload_shelf_id: Option<&str>,
    think: ThinkLevel,
    cancel: &Arc<AtomicBool>,
    emit: impl Fn(&str, serde_json::Value),
    started_emit: &std::sync::Once,
) -> Result<ChatOutput> {
    emit("status", json!({ "stage": "thinking" }));
    let files = if turn.stuffed {
        Vec::new()
    } else {
        catalog_for_turn(ctx, shelf_id, upload_shelf_id)
    };
    let shelf_ok = !files.is_empty();
    let chats_ok = Conversations::has_other_messages(&ctx.paths, thread_id);
    let mut used = tools::ToolUse::default();
    let mut collected = ChatOutput::default();
    let mut rounds = 0usize;
    let mut answer_only = false;
    let mut did_answer_retry = false;
    let mut thinking = match think {
        ThinkLevel::Deep => ChatThinking::Deep,
        ThinkLevel::Off | ThinkLevel::Light => ChatThinking::Off,
    };

    loop {
        if cancel.load(Ordering::Relaxed) {
            break;
        }
        let paging = turn
            .sources
            .iter()
            .any(|s| focus::window_is_truncated(ctx, s));
        let named_or_upload =
            upload_shelf_id.is_some() || turn.sources.iter().any(focus::is_open_window);
        let max_rounds = focus::max_tool_rounds(think, named_or_upload, paging);
        let online = crate::core::read_lock(&ctx.settings).allow_online_research;
        let allowed =
            tools::ToolSet::new(shelf_ok, !turn.sources.is_empty(), online, chats_ok, &used);
        let offer_tools = !answer_only && rounds < max_rounds && allowed.any();
        let mut options = ChatOptions::stream(0.7, answer_token_budget(ctx));
        options.thinking = thinking;
        if offer_tools {
            options.tools = Some(allowed.schema(&tools::labels_for_schema(&files)));
            options.tool_choice = Some("auto".into());
        }

        // Hide tool dumps on the forced answer round too, so a leftover call
        // does not become the visible reply.
        let mut holdback = tools::AnswerHoldback::new(offer_tools || answer_only);
        let output = engine
            .complete(&turn.messages, options, cancel, |event| {
                started_emit.call_once(|| emit("started", json!({})));
                match event {
                    StreamEvent::Thinking(delta) => {
                        emit("thinking", json!({ "text": delta }));
                    }
                    StreamEvent::Answer(delta) => {
                        if let Some(flush) = holdback.push(delta) {
                            emit("delta", json!({ "text": flush }));
                        }
                    }
                    StreamEvent::PromoteAnswerToThinking => {
                        emit("promote", json!({}));
                    }
                }
            })
            .await?;

        if !output.thinking.is_empty() {
            if !collected.thinking.is_empty() {
                collected.thinking.push('\n');
            }
            collected.thinking.push_str(&output.thinking);
        }

        let hidden = holdback.take_hidden();
        if cancel.load(Ordering::Relaxed) {
            collected.answer = holdback.visible_answer(&hidden, &output.answer);
            collected.finish_reason = output.finish_reason;
            break;
        }

        let calls = if offer_tools {
            let mut calls = tools::merge_tool_calls(output.tool_calls.clone(), &output.answer);
            if calls.is_empty() && !hidden.is_empty() {
                calls = tools::parse_tool_calls_from_text(&hidden);
            }
            calls
        } else {
            Vec::new()
        };

        if !calls.is_empty() && rounds < max_rounds && !answer_only {
            turn.messages.push(tools::assistant_tool_message(&calls));
            for call in &calls {
                if cancel.load(Ordering::Relaxed) {
                    break;
                }
                let hint = tools::status_hint(call, &turn.sources);
                emit_tool_status(&emit, &hint);
                let online = crate::core::read_lock(&ctx.settings).allow_online_research;
                let outcome = tools::run_tool(
                    call,
                    &tools::ToolCtx {
                        ctx,
                        thread_id,
                        shelf_id,
                        upload_shelf_id,
                        files: &files,
                        sources: &turn.sources,
                        budget: turn.budget,
                        think,
                        allowed: tools::ToolSet::new(
                            shelf_ok,
                            !turn.sources.is_empty(),
                            online,
                            chats_ok,
                            &used,
                        ),
                        cancel: cancel.as_ref(),
                    },
                )
                .await;
                if let Some(file) = outcome.file.as_deref() {
                    if hint.file.as_deref() != Some(file) {
                        emit_tool_status(
                            &emit,
                            &tools::StatusHint {
                                stage: hint.stage,
                                file: Some(file.to_string()),
                            },
                        );
                    }
                }
                tools::note_use(&mut used, call, &outcome.change);
                tools::apply_change(&mut turn.sources, outcome.change);
                turn.messages
                    .push(tools::tool_result_message(call, outcome.message));
            }
            if cancel.load(Ordering::Relaxed) {
                collected.answer = holdback.visible_answer(&hidden, &output.answer);
                collected.finish_reason = output.finish_reason;
                break;
            }
            rounds += 1;
            let after = tools::ToolSet::new(
                shelf_ok,
                !turn.sources.is_empty(),
                crate::core::read_lock(&ctx.settings).allow_online_research,
                chats_ok,
                &used,
            );
            if !after.follow_up_useful() {
                answer_only = true;
                emit("status", json!({ "stage": "thinking" }));
            }
            continue;
        }

        let answer = holdback.visible_answer(&hidden, &output.answer);
        if !holdback.released() && !answer.is_empty() {
            started_emit.call_once(|| emit("started", json!({})));
            emit("delta", json!({ "text": answer }));
        }
        if answer.is_empty() && !did_answer_retry {
            did_answer_retry = true;
            answer_only = true;
            thinking = ChatThinking::Off;
            emit("status", json!({ "stage": "thinking" }));
            continue;
        }
        collected.answer = answer;
        collected.finish_reason = output.finish_reason;
        break;
    }
    if should_fail_empty_answer(&collected.answer, cancel.load(Ordering::Relaxed)) {
        return Err(anyhow!("empty generation"));
    }
    Ok(collected)
}

fn should_fail_empty_answer(answer: &str, cancelled: bool) -> bool {
    !cancelled && answer.trim().is_empty()
}

fn should_emit_reading(library_id: Option<&str>, upload_id: Option<&str>) -> bool {
    library_id.is_some() || upload_id.is_some()
}

fn emit_tool_status(emit: &impl Fn(&str, serde_json::Value), hint: &tools::StatusHint) {
    match &hint.file {
        Some(file) if !file.is_empty() => {
            emit("status", json!({ "stage": hint.stage, "file": file }));
        }
        _ => emit("status", json!({ "stage": hint.stage })),
    }
}

/// Delete a conversation and any hidden upload Shelf tied to it.
pub fn delete_thread(ctx: &Arc<Ctx>, thread_id: &str) -> Result<()> {
    let meta = Conversations::get(&ctx.paths, thread_id);
    Conversations::delete(&ctx.paths, thread_id)?;
    if let Err(error) = ctx.search.remove_thread(thread_id) {
        log::warn!("remove thread from index: {error:#}");
    }
    let shelf_id = meta
        .as_ref()
        .and_then(|t| t.upload_shelf_id.clone())
        .or_else(|| {
            crate::core::read_lock(&ctx.library)
                .conversation_shelf(thread_id)
                .map(|s| s.id.clone())
        });
    if let Some(shelf_id) = shelf_id {
        ctx.ingest_queue.cancel_shelf(&shelf_id);
        let doc_ids = {
            let mut library = crate::core::write_lock(&ctx.library);
            library.remove_shelf(&ctx.paths, &shelf_id)?
        };
        if let Err(error) = ctx.search.remove_shelf(&shelf_id) {
            log::warn!("remove conversation shelf from index: {error:#}");
        }
        crate::ingest::remove_documents(ctx, &shelf_id, &doc_ids);
    }
    Ok(())
}

struct PreparedTurn {
    messages: Vec<ChatMessage>,
    sources: Vec<SourcePassage>,
    stuffed: bool,
    budget: usize,
}

fn turn_shelf_ids<'a>(
    shelf_id: Option<&'a str>,
    upload_shelf_id: Option<&'a str>,
) -> (Option<&'a str>, Option<&'a str>) {
    let library = shelf_id.filter(|id| Some(*id) != upload_shelf_id);
    (library, upload_shelf_id)
}

fn catalog_for_turn(
    ctx: &Ctx,
    library_id: Option<&str>,
    upload_id: Option<&str>,
) -> Vec<tools::ShelfFile> {
    let mut files = Vec::new();
    if let Some(id) = library_id {
        files.extend(tools::catalog(ctx, id));
    }
    if let Some(id) = upload_id {
        if Some(id) != library_id {
            files.extend(tools::catalog(ctx, id));
        }
    }
    files
}

struct Retrieved {
    passages: Vec<SourcePassage>,
    stuffed: bool,
}

impl Retrieved {
    fn empty() -> Self {
        Self {
            passages: Vec::new(),
            stuffed: true,
        }
    }
}

struct RetrieveOpts<'a> {
    extra_queries: &'a [String],
    think: ThinkLevel,
    budget: usize,
    focus_doc_ids: &'a [String],
    prefer_coverage: bool,
    attachment: bool,
}

fn retrieve_from_shelf(
    ctx: &Ctx,
    shelf_id: &str,
    text: &str,
    opts: RetrieveOpts<'_>,
) -> Result<Retrieved> {
    let plan = retrieve_plan(opts.think);
    if let Some(full) = try_stuff_shelf_docs(ctx, shelf_id, opts.budget) {
        return Ok(Retrieved {
            passages: full,
            stuffed: true,
        });
    }
    if opts.prefer_coverage && !opts.focus_doc_ids.is_empty() {
        let mut passages = Vec::new();
        let share = (opts.budget / opts.focus_doc_ids.len()).max(256);
        for id in opts.focus_doc_ids {
            passages.extend(focus::coverage_passages(ctx, shelf_id, id, share));
        }
        if !passages.is_empty() {
            if plan.expand_top > 0 {
                passages = expand_top_files(
                    ctx,
                    shelf_id,
                    passages,
                    opts.budget,
                    plan.expand_top,
                    opts.focus_doc_ids,
                );
            }
            return Ok(Retrieved {
                passages,
                stuffed: false,
            });
        }
    }
    let relaxed = crate::core::read_lock(&ctx.library)
        .shelf(shelf_id)
        .is_some_and(|s| s.thread_id.is_some());
    let files = shelf_files(ctx, shelf_id);
    let preserve_order = !opts.extra_queries.is_empty();
    let (hits, named) = if opts.extra_queries.is_empty() {
        ctx.search
            .search_and_merge_named(text, shelf_id, &files, plan.search_limit)?
    } else {
        let mut queries = Vec::with_capacity(1 + opts.extra_queries.len());
        queries.push(text.to_string());
        queries.extend(opts.extra_queries.iter().cloned());
        ctx.search
            .search_fused(&queries, shelf_id, &files, plan.search_limit)?
    };
    let mut named = named;
    for id in opts.focus_doc_ids {
        if !named.iter().any(|n| n == id) {
            named.push(id.clone());
        }
    }
    let mut overlap_tokens = ctx.search.query_tokens(text);
    for extra in opts.extra_queries {
        overlap_tokens.extend(ctx.search.query_tokens(extra));
    }
    let caps = if opts.attachment {
        focus::attachment_caps(opts.think)
    } else {
        plan.caps
    };
    let mut gated = if relaxed || opts.attachment {
        gate::gate_passages_named_with(hits, &[], &named, caps, preserve_order)
    } else {
        gate::gate_passages_named_with(hits, &overlap_tokens, &named, caps, preserve_order)
    };
    gated = neighbors::widen_neighbor_passages(ctx, shelf_id, gated, plan.neighbor_radius);
    if plan.expand_top > 0 && (!relaxed || opts.attachment) {
        gated = expand_top_files(
            ctx,
            shelf_id,
            gated,
            opts.budget,
            plan.expand_top,
            opts.focus_doc_ids,
        );
    }
    Ok(Retrieved {
        passages: gated,
        stuffed: false,
    })
}

fn prepare_turn(
    ctx: &Ctx,
    thread_id: &str,
    text: &str,
    shelf_id: Option<&str>,
    upload_shelf_id: Option<&str>,
    user_message_id: &str,
    extra_queries: &[String],
    library_think: ThinkLevel,
    focus_docs: &[String],
) -> Result<PreparedTurn> {
    let requested = ctx.context_budget();
    let budget = retrieval_budget(ctx, requested);
    let (library_id, upload_id) = turn_shelf_ids(shelf_id, upload_shelf_id);
    let named_attachment = !focus_docs.is_empty();
    let prefer_coverage = named_attachment && focus::whole_document_intent(text);
    let upload_budget = focus::upload_budget_chars(
        budget,
        upload_id.is_some(),
        named_attachment,
        prefer_coverage,
    );

    let upload = match upload_id {
        Some(id) if upload_budget >= 64 => retrieve_from_shelf(
            ctx,
            id,
            text,
            RetrieveOpts {
                extra_queries,
                think: ThinkLevel::Deep,
                budget: upload_budget,
                focus_doc_ids: focus_docs,
                prefer_coverage,
                attachment: true,
            },
        )?,
        Some(_) => Retrieved {
            passages: Vec::new(),
            stuffed: false,
        },
        None => Retrieved::empty(),
    };
    let upload_sources = gate::fit_passages(upload.passages, upload_budget);
    let remaining = budget.saturating_sub(tools::sources_cost(&upload_sources));
    let library_extras = if named_attachment {
        &[][..]
    } else {
        extra_queries
    };
    let library = match library_id {
        Some(id) if remaining >= 64 => retrieve_from_shelf(
            ctx,
            id,
            text,
            RetrieveOpts {
                extra_queries: library_extras,
                think: library_think,
                budget: remaining,
                focus_doc_ids: &[],
                prefer_coverage: false,
                attachment: false,
            },
        )?,
        Some(_) => Retrieved {
            passages: Vec::new(),
            stuffed: false,
        },
        None => Retrieved::empty(),
    };
    let library_sources = gate::fit_passages(library.passages, remaining);
    let stuffed = library.stuffed && upload.stuffed;
    let mut sources = upload_sources;
    let first = tools::next_sid_number(&sources);
    let mut library_tail = library_sources;
    for (offset, passage) in library_tail.iter_mut().enumerate() {
        passage.sid = format!("S{}", first + offset as u32);
    }
    sources.extend(library_tail);

    let (shelf_name, shelf_inventory) = shelf_prompt_bits(ctx, library_id, upload_id);
    let mut named_files = Vec::new();
    if let Some(id) = upload_id {
        named_files.extend(focus::named_files_on_shelf(ctx, id, text));
        if named_files.is_empty() {
            for doc_id in focus_docs {
                if let Some(meta) = crate::core::read_lock(&ctx.library).document(id, doc_id) {
                    named_files.push((id.to_string(), doc_id.clone(), meta.file_name));
                }
            }
        }
    }
    if let Some(id) = library_id {
        named_files.extend(focus::named_files_on_shelf(ctx, id, text));
    }
    let named_notes = focus::format_named_file_notes(ctx, &named_files);
    let settings = crate::core::read_lock(&ctx.settings);
    let house_rules =
        crate::limits::clip_chars(&settings.house_rules, crate::limits::HOUSE_RULES_MAX_CHARS);
    let online = settings.allow_online_research;
    drop(settings);
    let avatar_name = Conversations::get(&ctx.paths, thread_id)
        .and_then(|thread| avatars::name_for(&thread.avatar_id).map(str::to_string))
        .unwrap_or_else(|| "Rebost".into());
    let system = build_system_prompt(
        &house_rules,
        shelf_name.as_deref(),
        shelf_inventory.as_deref(),
        named_notes.as_deref(),
        stuffed,
        (library_id.is_some() || upload_id.is_some()) && !stuffed,
        online,
        &avatar_name,
    );

    let mut messages = vec![ChatMessage::text("system", system)];
    for previous in Conversations::recent_history(
        &ctx.paths,
        thread_id,
        HISTORY_MAX_MESSAGES,
        HISTORY_MAX_CHARS,
    ) {
        if previous.id == user_message_id {
            continue;
        }
        messages.push(ChatMessage::text(
            previous.role.clone(),
            gate::truncate_at_boundary(&previous.text, HISTORY_MESSAGE_MAX_CHARS),
        ));
    }
    messages.push(ChatMessage::text(
        "user",
        build_user_content(text, &sources, &[]),
    ));
    Ok(PreparedTurn {
        messages,
        sources,
        stuffed,
        budget,
    })
}

fn chat_spawn_plan(ctx: &Ctx) -> Option<crate::engine::tune::SpawnPlan> {
    let profile = crate::engine::catalog::MachineProfile::detect(ctx.paths.base());
    let pin = crate::engine::preferred_engine_pin().ok()?;
    let hint = crate::core::read_lock(&ctx.settings)
        .active_model
        .as_ref()
        .map(|model| crate::engine::tune::ModelHint::from_active(model, &ctx.paths.models_dir()));
    Some(match hint.as_ref() {
        Some(model) => crate::engine::tune::SpawnPlan::for_model(&profile, pin, Some(model)),
        None => crate::engine::tune::SpawnPlan::from_profile(&profile, pin),
    })
}

fn answer_token_budget(ctx: &Ctx) -> u32 {
    chat_spawn_plan(ctx)
        .map(|plan| plan.answer_tokens)
        .unwrap_or_else(|| crate::engine::tune::max_answer_tokens(4096))
}

fn retrieval_budget(ctx: &Ctx, requested: usize) -> usize {
    match chat_spawn_plan(ctx) {
        Some(plan) => crate::engine::tune::retrieval_char_budget_with(
            plan.context_tokens,
            plan.answer_tokens,
            requested,
        ),
        None => requested,
    }
}

fn stuffed_file_cost(title: &str, bytes: u64) -> usize {
    (bytes as usize)
        .saturating_add(title.len())
        .saturating_add(64)
}

pub(super) struct RetrievePlan {
    pub search_limit: usize,
    pub expand_top: usize,
    pub extra_queries: usize,
    pub neighbor_radius: usize,
    pub caps: gate::GateCaps,
}

pub(super) fn retrieve_plan(level: ThinkLevel) -> RetrievePlan {
    match level {
        ThinkLevel::Off => RetrievePlan {
            search_limit: 24,
            expand_top: 0,
            extra_queries: 0,
            neighbor_radius: neighbors::OFF_RADIUS_CHARS,
            caps: gate::GateCaps::default(),
        },
        ThinkLevel::Light => RetrievePlan {
            search_limit: 24,
            expand_top: 0,
            extra_queries: 3,
            neighbor_radius: neighbors::LIGHT_RADIUS_CHARS,
            caps: gate::GateCaps {
                relative_floor: 0.15,
                ..gate::GateCaps::default()
            },
        },
        ThinkLevel::Deep => RetrievePlan {
            search_limit: 32,
            expand_top: 2,
            extra_queries: 3,
            neighbor_radius: neighbors::DEEP_RADIUS_CHARS,
            caps: gate::GateCaps {
                max_passages: 12,
                max_per_doc: 4,
                max_per_named: 8,
                relative_floor: 0.12,
            },
        },
    }
}

fn shelf_think_level(ctx: &Ctx, shelf_id: Option<&str>) -> ThinkLevel {
    let Some(id) = shelf_id else {
        return ThinkLevel::Off;
    };
    crate::core::read_lock(&ctx.library)
        .shelf(id)
        .map(|s| s.think_level)
        .unwrap_or_default()
}

async fn extra_search_for_turn(
    engine: &Arc<Engine>,
    ctx: &Ctx,
    text: &str,
    library_id: Option<&str>,
    upload_id: Option<&str>,
    think: ThinkLevel,
    named_attachment: bool,
    prefer_coverage: bool,
    cancel: &Arc<AtomicBool>,
    emit: impl Fn(&str, serde_json::Value),
) -> Vec<String> {
    let count = retrieve_plan(think).extra_queries;
    if count == 0 || cancel.load(Ordering::Relaxed) {
        return Vec::new();
    }
    let budget = retrieval_budget(ctx, ctx.context_budget());
    let upload_needs = upload_id.is_some_and(|id| {
        !prefer_coverage && matches!(stuff_plan(ctx, id, budget), StuffPlan::Search)
    });
    let library_needs = library_id.is_some_and(|id| {
        !named_attachment && matches!(stuff_plan(ctx, id, budget), StuffPlan::Search)
    });
    if !upload_needs && !library_needs {
        return Vec::new();
    }
    emit("status", json!({ "stage": "looking" }));
    extra_search_queries(engine, text, count, cancel).await
}

fn expand_top_files(
    ctx: &Ctx,
    shelf_id: &str,
    passages: Vec<SourcePassage>,
    budget: usize,
    top_n: usize,
    focus_doc_ids: &[String],
) -> Vec<SourcePassage> {
    if top_n == 0 || passages.is_empty() {
        return passages;
    }
    let mut ranked_ids: Vec<String> = Vec::new();
    for id in focus_doc_ids {
        if !ranked_ids.iter().any(|existing| existing == id) {
            ranked_ids.push(id.clone());
        }
        if ranked_ids.len() >= top_n {
            break;
        }
    }
    for passage in &passages {
        if !ranked_ids.iter().any(|id| id == &passage.document_id) {
            ranked_ids.push(passage.document_id.clone());
        }
        if ranked_ids.len() >= top_n {
            break;
        }
    }
    let mut expanded = Vec::new();
    let mut used = 0usize;
    let mut replaced: HashSet<String> = HashSet::new();
    for id in &ranked_ids {
        let Some(meta) = crate::core::read_lock(&ctx.library).document(shelf_id, id) else {
            continue;
        };
        let path = ctx.paths.extracted_path(shelf_id, id);
        let Ok(info) = std::fs::metadata(&path) else {
            continue;
        };
        let cost = stuffed_file_cost(&meta.file_name, info.len());
        if used + cost > budget {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue;
        };
        used += cost;
        replaced.insert(id.clone());
        let score = passages
            .iter()
            .filter(|p| &p.document_id == id)
            .map(|p| p.score)
            .fold(0.0f32, f32::max);
        expanded.push(SourcePassage {
            sid: String::new(),
            document_id: id.clone(),
            shelf_id: shelf_id.to_string(),
            title: meta.file_name,
            section: None,
            page_start: None,
            page_end: meta.pages,
            body: text,
            path: meta.path,
            score,
        });
    }
    for passage in passages {
        if replaced.contains(&passage.document_id) {
            continue;
        }
        expanded.push(passage);
    }
    expanded.sort_by(|a, b| b.score.total_cmp(&a.score));
    expanded
}

/// Send the whole extracted file when it fits the remaining window.
///
/// Local AIs here run at 4k–8k context. Prefill is the slow part: the install
/// benchmark sizes this budget so prompt processing stays around two seconds,
/// then the spawn plan caps it so the prompt plus the answer still fit in `-c`.
/// When the files are smaller than that, stuffing beats search (no missed
/// passage). Longer files go through Tantivy.
fn try_stuff_shelf_docs(ctx: &Ctx, shelf_id: &str, budget: usize) -> Option<Vec<SourcePassage>> {
    let StuffPlan::Fits(planned) = stuff_plan(ctx, shelf_id, budget) else {
        return None;
    };
    let mut sources = Vec::with_capacity(planned.len());
    for (doc, path) in planned {
        let text = std::fs::read_to_string(&path).ok()?;
        sources.push(SourcePassage {
            sid: String::new(),
            document_id: doc.id.clone(),
            shelf_id: shelf_id.to_string(),
            title: doc.file_name.clone(),
            section: None,
            page_start: None,
            page_end: doc.pages,
            body: text,
            path: doc.path.clone(),
            score: 1.0,
        });
    }
    Some(sources)
}

enum StuffPlan {
    Empty,
    Fits(Vec<(DocumentMeta, PathBuf)>),
    Search,
}

/// Ready extracted files that fit `budget`, or why they cannot be sent whole.
fn stuff_plan(ctx: &Ctx, shelf_id: &str, budget: usize) -> StuffPlan {
    let docs = {
        let library = crate::core::read_lock(&ctx.library);
        library
            .documents(shelf_id)
            .into_iter()
            .filter(|d| d.status == DocStatus::Ready)
            .collect::<Vec<_>>()
    };
    if docs.is_empty() {
        return StuffPlan::Empty;
    }
    let mut planned = Vec::with_capacity(docs.len());
    let mut used = 0usize;
    for doc in docs {
        let path = ctx.paths.extracted_path(shelf_id, &doc.id);
        let Ok(info) = std::fs::metadata(&path) else {
            return StuffPlan::Search;
        };
        used = used.saturating_add(stuffed_file_cost(&doc.file_name, info.len()));
        if used > budget {
            return StuffPlan::Search;
        }
        planned.push((doc, path));
    }
    StuffPlan::Fits(planned)
}

fn shelf_files(ctx: &Ctx, shelf_id: &str) -> Vec<(String, String)> {
    crate::core::read_lock(&ctx.library)
        .documents(shelf_id)
        .into_iter()
        .filter(|d| d.status == DocStatus::Ready)
        .map(|d| (d.id, d.file_name))
        .collect()
}

fn shelf_inventory(ctx: &Ctx, shelf_id: &str) -> Option<(String, String)> {
    let library = crate::core::read_lock(&ctx.library);
    let name = library.shelf(shelf_id)?.name.clone();
    let docs = library.documents(shelf_id);
    let labels = shelf_file_labels(
        docs.iter()
            .map(|d| (d.file_name.as_str(), d.rel_path.as_str())),
    );
    let inventory = format_shelf_inventory(&name, &labels);
    Some((name, inventory))
}

fn shelf_prompt_bits(
    ctx: &Ctx,
    library_id: Option<&str>,
    upload_id: Option<&str>,
) -> (Option<String>, Option<String>) {
    let library = library_id.and_then(|id| shelf_inventory(ctx, id));
    let upload = upload_id.and_then(|id| shelf_inventory(ctx, id));
    match (library, upload) {
        (None, None) => (None, None),
        (Some((name, inventory)), None) | (None, Some((name, inventory))) => {
            (Some(name), Some(inventory))
        }
        (Some((name, library_inv)), Some((_, upload_inv))) => {
            (Some(name), Some(format!("{library_inv}\n{upload_inv}")))
        }
    }
}

#[cfg(test)]
mod cancel_tests {
    use super::*;
    use crate::core::NoopEvents;
    use crate::ingest::extract::ExtractorSettings;
    use crate::paths::Paths;
    use std::sync::atomic::Ordering;

    struct Bundle {
        chat: Arc<ChatService>,
        _dir: tempfile::TempDir,
    }

    fn test_chat() -> Bundle {
        let dir = tempfile::tempdir().unwrap();
        let paths = Paths::new(dir.path().join("appdata"));
        let ctx = Ctx::new(paths, Arc::new(NoopEvents), ExtractorSettings::default()).unwrap();
        let engine = Engine::new(ctx.clone());
        Bundle {
            chat: ChatService::new(ctx, engine),
            _dir: dir,
        }
    }

    #[test]
    fn cancel_unknown_id_is_silent() {
        let bundle = test_chat();
        bundle.chat.cancel("no-such-message");
        assert_eq!(bundle.chat.cancel_count(), 0);
    }

    #[test]
    fn cancel_sets_registered_flag() {
        let bundle = test_chat();
        let flag = bundle.chat.register_cancel_for_test("m1");
        assert!(!flag.load(Ordering::Relaxed));
        bundle.chat.cancel("m1");
        assert!(flag.load(Ordering::Relaxed));
    }

    struct CollectChat(std::sync::Mutex<Vec<serde_json::Value>>);

    impl crate::core::Events for CollectChat {
        fn emit(&self, event: &str, payload: serde_json::Value) {
            if event == "rebost://chat" {
                self.0.lock().unwrap().push(payload);
            }
        }
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn cancel_while_waiting_for_the_generation_slot_skips_the_engine() {
        let dir = tempfile::tempdir().unwrap();
        let paths = Paths::new(dir.path().join("appdata"));
        let events = Arc::new(CollectChat(std::sync::Mutex::new(Vec::new())));
        let ctx = Ctx::new(paths, events.clone(), ExtractorSettings::default()).unwrap();
        let engine = Engine::new(ctx.clone());
        let chat = ChatService::new(ctx.clone(), engine);
        let thread = Conversations::create(&ctx.paths, None).unwrap();

        let guard = chat.generation.lock().await;
        let chat_send = chat.clone();
        let thread_id = thread.id.clone();
        let handle = tokio::spawn(async move {
            chat_send
                .send_message(&thread_id, "Hello there, please answer.", None)
                .await
        });

        let deadline = tokio::time::Instant::now() + std::time::Duration::from_secs(2);
        let mut message_id = None;
        let mut saw_waiting = false;
        while tokio::time::Instant::now() < deadline {
            {
                let captured = events.0.lock().unwrap();
                if message_id.is_none() {
                    message_id = captured.iter().find_map(|payload| {
                        if payload.get("kind").and_then(|kind| kind.as_str()) == Some("queued") {
                            payload
                                .get("messageId")
                                .and_then(|id| id.as_str())
                                .map(str::to_string)
                        } else {
                            None
                        }
                    });
                }
                saw_waiting = captured.iter().any(|payload| {
                    payload.get("kind").and_then(|kind| kind.as_str()) == Some("status")
                        && payload.get("stage").and_then(|stage| stage.as_str()) == Some("waiting")
                });
            }
            if message_id.is_some() && saw_waiting {
                break;
            }
            tokio::time::sleep(std::time::Duration::from_millis(10)).await;
        }
        let message_id = message_id.expect("queued event while waiting for the slot");
        assert!(
            saw_waiting,
            "waiting status while another answer holds the slot"
        );
        chat.cancel(&message_id);
        drop(guard);

        let message = handle.await.unwrap().unwrap();
        assert_eq!(message.status, "stopped");
        let captured = events.0.lock().unwrap();
        assert!(
            captured.iter().all(|payload| {
                payload.get("kind").and_then(|kind| kind.as_str()) != Some("started")
            }),
            "engine should not have started"
        );
    }

    #[test]
    fn notify_send_failed_emits_an_error_for_the_thread() {
        let dir = tempfile::tempdir().unwrap();
        let paths = Paths::new(dir.path().join("appdata"));
        let events = Arc::new(CollectChat(std::sync::Mutex::new(Vec::new())));
        let ctx = Ctx::new(paths, events.clone(), ExtractorSettings::default()).unwrap();
        let engine = Engine::new(ctx.clone());
        let chat = ChatService::new(ctx, engine);
        chat.notify_send_failed("t1");
        let captured = events.0.lock().unwrap();
        assert_eq!(captured.len(), 1);
        assert_eq!(
            captured[0].get("kind").and_then(|kind| kind.as_str()),
            Some("error")
        );
        assert_eq!(
            captured[0].get("threadId").and_then(|id| id.as_str()),
            Some("t1")
        );
        assert_eq!(
            captured[0].get("messageId").and_then(|id| id.as_str()),
            Some("")
        );
    }

    #[test]
    fn a_blank_finished_turn_is_a_failure() {
        assert!(should_fail_empty_answer("", false));
        assert!(should_fail_empty_answer("   ", false));
        assert!(!should_fail_empty_answer("Hello", false));
        assert!(!should_fail_empty_answer("", true));
    }
}

#[cfg(test)]
mod prepare_tests {
    use super::*;
    use crate::core::NoopEvents;
    use crate::engine::ToolCall;
    use crate::ingest::extract::ExtractorSettings;
    use crate::ingest::ProcessJob;
    use crate::paths::Paths;
    use crate::types::SourceType;

    struct Fixture {
        ctx: Arc<Ctx>,
        shelf: crate::shelf::Shelf,
        _dir: tempfile::TempDir,
    }

    async fn shelf_with_file(name: &str, body: &str) -> Fixture {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("Shelves");
        let paths = Paths::new(dir.path().join("appdata"));
        let ctx = Ctx::new(paths, Arc::new(NoopEvents), ExtractorSettings::default()).unwrap();
        let shelf = {
            let mut library = crate::core::write_lock(&ctx.library);
            library.create_shelf(&ctx.paths, "Notes", &root).unwrap()
        };
        let file = dir.path().join(name);
        std::fs::write(&file, body).unwrap();
        let copied =
            crate::shelf::import_into_shelf(&shelf, &[file], crate::shelf::MAX_FILES_PER_SHELF)
                .unwrap()
                .files;
        let abs = copied.into_iter().next().unwrap();
        let rel = abs
            .strip_prefix(&shelf.managed_path)
            .unwrap()
            .to_string_lossy()
            .to_string();
        crate::ingest::process_file(
            &ctx,
            &ProcessJob {
                shelf_id: shelf.id.clone(),
                source_id: crate::shelf::Shelf::IMPORTED_SOURCE.to_string(),
                source_type: SourceType::Imported,
                source_label: "Imported".into(),
                abs_path: abs,
                rel_path: rel,
                force: false,
                epoch: 0,
            },
        )
        .await
        .unwrap();
        Fixture {
            ctx,
            shelf,
            _dir: dir,
        }
    }

    fn tool_ctx<'a>(
        ctx: &'a Ctx,
        thread_id: &'a str,
        shelf_id: &'a str,
        files: &'a [tools::ShelfFile],
        sources: &'a [SourcePassage],
        budget: usize,
    ) -> tools::ToolCtx<'a> {
        tools::ToolCtx {
            ctx,
            thread_id,
            shelf_id: Some(shelf_id),
            upload_shelf_id: None,
            files,
            sources,
            budget,
            think: ThinkLevel::Off,
            allowed: tools::ToolSet::new(
                true,
                !sources.is_empty(),
                false,
                true,
                &tools::ToolUse::default(),
            ),
            cancel: idle_cancel(),
        }
    }

    fn idle_cancel() -> &'static AtomicBool {
        static FLAG: AtomicBool = AtomicBool::new(false);
        &FLAG
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn prepare_turn_puts_shelf_passages_in_the_prompt() {
        let fixture = shelf_with_file(
            "handbook.md",
            "# Staff handbook\n\nThe office kitchen is restocked every Tuesday morning.\n",
        )
        .await;
        let thread =
            Conversations::create(&fixture.ctx.paths, Some(fixture.shelf.id.clone())).unwrap();
        let prepared = prepare_turn(
            &fixture.ctx,
            &thread.id,
            "When is the kitchen restocked?",
            Some(&fixture.shelf.id),
            None,
            "m_none",
            &[],
            ThinkLevel::Off,
            &[],
        )
        .unwrap();
        assert!(
            !prepared.sources.is_empty(),
            "expected retrieved passages, got none"
        );
        let user = prepared
            .messages
            .iter()
            .find(|m| m.role == "user")
            .expect("user message");
        assert!(
            user.as_text().to_lowercase().contains("tuesday")
                || prepared
                    .sources
                    .iter()
                    .any(|s| s.body.to_lowercase().contains("tuesday")),
            "prompt should carry the handbook passage"
        );
        let system = prepared.messages[0].as_text();
        assert!(system.contains("Notes"));
        assert_eq!(
            prepared.sources.len(),
            1,
            "a short file should be sent whole, not searched"
        );
        assert!(prepared.sources[0].body.contains("Staff handbook"));
        assert!(prepared.sources[0].body.to_lowercase().contains("tuesday"));
        assert!(!user.as_text().contains("OLDER CONVERSATION NOTES"));
        assert!(system.contains("recent turns from this conversation only"));
        assert!(!system.contains("search_chats"));
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn prepare_turn_keeps_the_library_shelf_and_appends_uploads() {
        let fixture = shelf_with_file(
            "handbook.md",
            "# Staff handbook\n\nThe office kitchen is restocked every Tuesday morning.\n",
        )
        .await;
        let thread =
            Conversations::create(&fixture.ctx.paths, Some(fixture.shelf.id.clone())).unwrap();
        let upload = {
            let mut library = crate::core::write_lock(&fixture.ctx.library);
            library
                .ensure_conversation_shelf(&fixture.ctx.paths, &thread.id)
                .unwrap()
        };
        let dest = upload.managed_path.join("invoice.md");
        std::fs::write(
            &dest,
            "# Invoice\n\nThe attached invoice total is 480 euros.\n",
        )
        .unwrap();
        crate::ingest::process_file(
            &fixture.ctx,
            &ProcessJob {
                shelf_id: upload.id.clone(),
                source_id: crate::shelf::Shelf::IMPORTED_SOURCE.to_string(),
                source_type: SourceType::Imported,
                source_label: "Imported".into(),
                abs_path: dest,
                rel_path: "invoice.md".into(),
                force: false,
                epoch: 0,
            },
        )
        .await
        .unwrap();

        let prepared = prepare_turn(
            &fixture.ctx,
            &thread.id,
            "When is the kitchen restocked, and what is the invoice total?",
            Some(&fixture.shelf.id),
            Some(&upload.id),
            "m_none",
            &[],
            ThinkLevel::Off,
            &[],
        )
        .unwrap();
        assert!(
            prepared
                .sources
                .iter()
                .any(|s| s.body.to_lowercase().contains("tuesday")),
            "library shelf should still be retrieved"
        );
        assert!(
            prepared
                .sources
                .iter()
                .any(|s| s.body.to_lowercase().contains("480")),
            "attached file should be included"
        );
        assert!(
            prepared.sources.iter().any(|s| s.shelf_id == upload.id),
            "attached file should be in sources"
        );
        assert!(
            prepared
                .sources
                .iter()
                .any(|s| s.shelf_id == fixture.shelf.id),
            "library shelf should be in sources"
        );
        assert!(prepared.messages[0].as_text().contains("Notes"));
        assert!(prepared.messages[0].as_text().contains("Uploaded files"));
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn prepare_turn_keeps_the_upload_to_its_share() {
        let fixture = shelf_with_file(
            "handbook.md",
            "# Staff handbook\n\nThe office kitchen is restocked every Tuesday morning.\n",
        )
        .await;
        let thread =
            Conversations::create(&fixture.ctx.paths, Some(fixture.shelf.id.clone())).unwrap();
        let mut upload = None;
        for i in 0..6 {
            let mut body = format!("# Zebra note {i}\n\n");
            body.push_str(
                &format!("The office zebra in building {i} lives in the east wing.\n").repeat(40),
            );
            upload =
                Some(add_upload_file(&fixture, &thread.id, &format!("zebra-{i}.md"), &body).await);
        }
        let upload = upload.expect("upload shelf");
        let prepared = prepare_turn(
            &fixture.ctx,
            &thread.id,
            "Where does the office zebra live, and when is the kitchen restocked?",
            Some(&fixture.shelf.id),
            Some(&upload.id),
            "m_none",
            &[],
            ThinkLevel::Off,
            &[],
        )
        .unwrap();
        let budget = retrieval_budget(&fixture.ctx, fixture.ctx.context_budget());
        let share = focus::upload_budget_chars(budget, true, false, false);
        let upload_cost: usize = prepared
            .sources
            .iter()
            .filter(|s| s.shelf_id == upload.id)
            .map(tools::passage_cost)
            .sum();
        assert!(
            upload_cost <= share,
            "attached files should leave room for the Shelf, cost={upload_cost} share={share} budget={budget}"
        );
        assert!(
            prepared.sources.iter().any(
                |s| s.shelf_id == fixture.shelf.id && s.body.to_lowercase().contains("tuesday")
            ),
            "library Shelf should still be retrieved"
        );
    }

    #[test]
    fn stuffed_file_cost_includes_title_and_wrapper() {
        assert_eq!(super::stuffed_file_cost("ab", 3), 2 + 3 + 64);
    }

    #[test]
    fn reading_status_only_when_a_shelf_is_in_play() {
        assert!(!super::should_emit_reading(None, None));
        assert!(super::should_emit_reading(Some("s_lib"), None));
        assert!(super::should_emit_reading(None, Some("s_up")));
        assert!(super::should_emit_reading(Some("s_lib"), Some("s_up")));
    }

    #[test]
    fn turn_shelf_ids_drops_a_library_id_that_is_the_upload_shelf() {
        assert_eq!(
            super::turn_shelf_ids(Some("s_lib"), Some("s_up")),
            (Some("s_lib"), Some("s_up"))
        );
        assert_eq!(
            super::turn_shelf_ids(Some("s_up"), Some("s_up")),
            (None, Some("s_up"))
        );
        assert_eq!(
            super::turn_shelf_ids(None, Some("s_up")),
            (None, Some("s_up"))
        );
    }

    #[test]
    fn retrieve_plan_matches_off_light_deep() {
        let off = retrieve_plan(ThinkLevel::Off);
        assert_eq!(off.extra_queries, 0);
        assert_eq!(off.expand_top, 0);
        assert_eq!(off.neighbor_radius, neighbors::OFF_RADIUS_CHARS);

        let light = retrieve_plan(ThinkLevel::Light);
        assert_eq!(light.extra_queries, 3);
        assert_eq!(light.expand_top, 0);
        assert_eq!(light.neighbor_radius, neighbors::LIGHT_RADIUS_CHARS);
        assert_eq!(light.caps.relative_floor, 0.15);

        let deep = retrieve_plan(ThinkLevel::Deep);
        assert_eq!(deep.extra_queries, 3);
        assert_eq!(deep.expand_top, 2);
        assert_eq!(deep.search_limit, 32);
        assert_eq!(deep.neighbor_radius, neighbors::DEEP_RADIUS_CHARS);
        assert_eq!(deep.caps.max_passages, 12);
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn prepare_turn_searches_when_the_file_is_too_long() {
        let mut body = String::from("# Encyclopedia\n\n");
        body.push_str(&"The office zebra lives in the east wing.\n".repeat(800));
        let fixture = shelf_with_file("encyclopedia.md", &body).await;
        let thread =
            Conversations::create(&fixture.ctx.paths, Some(fixture.shelf.id.clone())).unwrap();
        let prepared = prepare_turn(
            &fixture.ctx,
            &thread.id,
            "Where does the office zebra live?",
            Some(&fixture.shelf.id),
            None,
            "m_none",
            &[],
            ThinkLevel::Off,
            &[],
        )
        .unwrap();
        assert!(
            !prepared.sources.is_empty(),
            "expected retrieved passages, got none"
        );
        let extracted = std::fs::read_to_string(
            fixture
                .ctx
                .paths
                .extracted_path(&fixture.shelf.id, &prepared.sources[0].document_id),
        )
        .unwrap();
        assert!(extracted.chars().count() > 20_000);
        assert!(
            prepared
                .sources
                .iter()
                .all(|s| s.body.chars().count() < extracted.chars().count()),
            "long files should be searched, not stuffed whole"
        );
        assert!(prepared
            .sources
            .iter()
            .any(|s| s.body.to_lowercase().contains("zebra")));
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn prepare_turn_fuses_extra_queries_when_the_file_is_long() {
        let mut body = String::from("# Encyclopedia\n\n");
        body.push_str(&"The office zebra lives in the east wing.\n".repeat(800));
        let fixture = shelf_with_file("encyclopedia.md", &body).await;
        let thread =
            Conversations::create(&fixture.ctx.paths, Some(fixture.shelf.id.clone())).unwrap();
        let prepared = prepare_turn(
            &fixture.ctx,
            &thread.id,
            "Where does it live?",
            Some(&fixture.shelf.id),
            None,
            "m_none",
            &["office zebra east wing".into()],
            ThinkLevel::Light,
            &[],
        )
        .unwrap();
        assert!(prepared
            .sources
            .iter()
            .any(|s| s.body.to_lowercase().contains("zebra")));
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn prepare_turn_does_not_stuff_earlier_chats() {
        let fixture = shelf_with_file(
            "handbook.md",
            "# Staff handbook\n\nThe office kitchen is restocked every Tuesday morning.\n",
        )
        .await;
        let now = chrono::Utc::now();
        fixture
            .ctx
            .search
            .index_message(
                "other_thread",
                "m_old",
                "user",
                "The office kitchen is restocked every Tuesday morning.",
                Some("en"),
                now,
            )
            .unwrap();
        let thread =
            Conversations::create(&fixture.ctx.paths, Some(fixture.shelf.id.clone())).unwrap();
        let prepared = prepare_turn(
            &fixture.ctx,
            &thread.id,
            "When is the kitchen restocked?",
            Some(&fixture.shelf.id),
            None,
            "m_none",
            &[],
            ThinkLevel::Off,
            &[],
        )
        .unwrap();
        let user = prepared
            .messages
            .iter()
            .find(|m| m.role == "user")
            .expect("user message");
        assert!(!user.as_text().contains("OLDER CONVERSATION NOTES"));
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn open_shelf_file_loads_a_long_file_into_sources() {
        let mut body = String::from("# Encyclopedia\n\n");
        body.push_str(&"The office zebra lives in the east wing.\n".repeat(800));
        let fixture = shelf_with_file("encyclopedia.md", &body).await;
        let files = super::tools::catalog(&fixture.ctx, &fixture.shelf.id);
        assert_eq!(files.len(), 1);
        let tool = tool_ctx(&fixture.ctx, "t", &fixture.shelf.id, &files, &[], 12_000);
        let outcome = super::tools::open_shelf_file(&tool, "encyclopedia.md", None);
        let source = match outcome.change {
            tools::SourceChange::OpenWindow { opened, .. } => opened,
            other => panic!("expected opened file, got {other:?}"),
        };
        assert_eq!(source.sid, "S1");
        assert!(source.body.to_lowercase().contains("zebra"));
        assert!(outcome.message.contains("[S1]"));
        assert!(matches!(
            super::tools::open_shelf_file(&tool, "no-such.md", None).change,
            tools::SourceChange::None
        ));
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn search_shelf_adds_a_fresh_excerpt() {
        let mut body = String::from("# Encyclopedia\n\n");
        body.push_str(&"Padding text so the file is too long to send whole.\n".repeat(400));
        body.push_str("The office zebra lives in the east wing.\n");
        body.push_str(&"More padding after the zebra sentence.\n".repeat(400));
        let fixture = shelf_with_file("encyclopedia.md", &body).await;
        let files = super::tools::catalog(&fixture.ctx, &fixture.shelf.id);
        let tool = tool_ctx(&fixture.ctx, "t", &fixture.shelf.id, &files, &[], 12_000);
        let call = ToolCall::function(
            "c1",
            tools::SEARCH_SHELF,
            serde_json::json!({ "query": "office zebra" }).to_string(),
        );
        let outcome = tools::run_tool(&call, &tool).await;
        let tools::SourceChange::Append(added) = outcome.change else {
            panic!("expected new excerpts, got {:?}", outcome.change);
        };
        assert!(added
            .iter()
            .any(|s| s.body.to_lowercase().contains("zebra")));
        assert!(outcome.message.contains("[S1]"));
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn look_around_widens_an_excerpt() {
        let mut body = String::from("# Encyclopedia\n\n");
        body.push_str("alpha paragraph before the hit.\n\n");
        body.push_str("The office zebra lives in the east wing.\n\n");
        body.push_str("omega paragraph after the hit.\n");
        body.push_str(&"Padding so stuffing does not apply.\n".repeat(800));
        let fixture = shelf_with_file("encyclopedia.md", &body).await;
        let files = super::tools::catalog(&fixture.ctx, &fixture.shelf.id);
        let excerpt = SourcePassage {
            sid: "S1".into(),
            document_id: files[0].id.clone(),
            shelf_id: fixture.shelf.id.clone(),
            title: "encyclopedia.md".into(),
            section: None,
            page_start: None,
            page_end: None,
            body: "The office zebra lives in the east wing.".into(),
            path: files[0].path.clone(),
            score: 1.0,
        };
        let sources = [excerpt];
        let tool = tool_ctx(
            &fixture.ctx,
            "t",
            &fixture.shelf.id,
            &files,
            &sources,
            12_000,
        );
        let call = ToolCall::function(
            "c1",
            tools::LOOK_AROUND,
            serde_json::json!({ "id": "S1" }).to_string(),
        );
        let outcome = tools::run_tool(&call, &tool).await;
        let tools::SourceChange::ReplaceOne(updated) = outcome.change else {
            panic!("expected widened excerpt, got {:?}", outcome.change);
        };
        assert_eq!(updated.sid, "S1");
        assert!(updated.body.contains("alpha"));
        assert!(updated.body.contains("omega"));
        assert!(updated.body.len() > sources[0].body.len());
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn search_chats_returns_notes_from_other_threads() {
        let dir = tempfile::tempdir().unwrap();
        let paths = Paths::new(dir.path().join("appdata"));
        let ctx = Ctx::new(paths, Arc::new(NoopEvents), ExtractorSettings::default()).unwrap();
        let now = chrono::Utc::now();
        ctx.search
            .index_message(
                "other",
                "m_old",
                "user",
                "The office move budget is twelve thousand euros.",
                Some("en"),
                now,
            )
            .unwrap();
        let files: Vec<tools::ShelfFile> = Vec::new();
        let tool = tools::ToolCtx {
            ctx: ctx.as_ref(),
            thread_id: "current",
            shelf_id: None,
            upload_shelf_id: None,
            files: &files,
            sources: &[],
            budget: 9_000,
            think: ThinkLevel::Off,
            allowed: tools::ToolSet::new(false, false, false, true, &tools::ToolUse::default()),
            cancel: idle_cancel(),
        };
        let call = ToolCall::function(
            "c1",
            tools::SEARCH_CHATS,
            serde_json::json!({ "query": "office move budget" }).to_string(),
        );
        let outcome = tools::run_tool(&call, &tool).await;
        assert!(matches!(outcome.change, tools::SourceChange::None));
        assert!(outcome.message.to_lowercase().contains("twelve thousand"));
        assert!(outcome.message.contains("do not cite"));
    }

    async fn add_upload_file(
        fixture: &Fixture,
        thread_id: &str,
        name: &str,
        body: &str,
    ) -> crate::shelf::Shelf {
        let upload = {
            let mut library = crate::core::write_lock(&fixture.ctx.library);
            library
                .ensure_conversation_shelf(&fixture.ctx.paths, thread_id)
                .unwrap()
        };
        let dest = upload.managed_path.join(name);
        std::fs::write(&dest, body).unwrap();
        crate::ingest::process_file(
            &fixture.ctx,
            &ProcessJob {
                shelf_id: upload.id.clone(),
                source_id: crate::shelf::Shelf::IMPORTED_SOURCE.to_string(),
                source_type: SourceType::Imported,
                source_label: "Imported".into(),
                abs_path: dest,
                rel_path: name.into(),
                force: false,
                epoch: 0,
            },
        )
        .await
        .unwrap();
        upload
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn prepare_turn_covers_a_named_attached_file() {
        let fixture = shelf_with_file(
            "handbook.md",
            "# Staff handbook\n\nThe office kitchen is restocked every Tuesday morning.\n",
        )
        .await;
        let thread =
            Conversations::create(&fixture.ctx.paths, Some(fixture.shelf.id.clone())).unwrap();
        let mut body = String::from("# ALPHA unique start\n\n");
        body.push_str(&"The office zebra lives in the east wing.\n".repeat(800));
        body.push_str("\n# OMEGA unique end\n");
        let upload = add_upload_file(&fixture, &thread.id, "encyclopedia.md", &body).await;
        let doc_id = crate::core::read_lock(&fixture.ctx.library)
            .documents(&upload.id)
            .into_iter()
            .next()
            .unwrap()
            .id;
        let extracted_path = fixture.ctx.paths.extracted_path(&upload.id, &doc_id);
        std::fs::write(&extracted_path, &body).unwrap();
        assert!(
            std::fs::read_to_string(&extracted_path)
                .unwrap()
                .chars()
                .count()
                > 20_000,
            "test extract should be the long file"
        );
        let covered = super::focus::coverage_passages(&fixture.ctx, &upload.id, &doc_id, 9_000);
        let covered_text = covered
            .iter()
            .map(|s| s.body.as_str())
            .collect::<Vec<_>>()
            .join("\n");
        assert!(
            covered_text.contains("ALPHA") && covered_text.contains("OMEGA"),
            "coverage_passages should sample both ends, got {covered_text:?}"
        );
        assert!(
            covered
                .iter()
                .map(|s| s.body.chars().count())
                .sum::<usize>()
                > 1_000,
            "coverage should spend the window, got {} passages / {} chars",
            covered.len(),
            covered
                .iter()
                .map(|s| s.body.chars().count())
                .sum::<usize>()
        );
        // A 4k machine (CI's 7 GB Linux runner) only has ~1k chars after
        // wrappers. The file should still keep both ends and spend the room.
        let tight_budget = 1_004;
        let tight =
            super::focus::coverage_passages(&fixture.ctx, &upload.id, &doc_id, tight_budget);
        let tight_text = tight
            .iter()
            .map(|s| s.body.as_str())
            .collect::<Vec<_>>()
            .join("\n");
        let tight_cost: usize = tight.iter().map(tools::passage_cost).sum();
        assert!(
            tight_text.contains("ALPHA") && tight_text.contains("OMEGA"),
            "a small window should still keep both ends, got {tight_text:?}"
        );
        assert!(
            tight_cost + 256 >= tight_budget,
            "a small window should still be spent, cost={tight_cost} budget={tight_budget}"
        );
        let prepared = prepare_turn(
            &fixture.ctx,
            &thread.id,
            "Summarize this doc: encyclopedia.md",
            Some(&fixture.shelf.id),
            Some(&upload.id),
            "m_none",
            &[],
            ThinkLevel::Off,
            &[doc_id],
        )
        .unwrap();
        let upload_text = prepared
            .sources
            .iter()
            .filter(|s| s.shelf_id == upload.id)
            .map(|s| s.body.as_str())
            .collect::<Vec<_>>()
            .join("\n");
        assert!(
            upload_text.contains("ALPHA"),
            "coverage should keep the start, got {upload_text:?}"
        );
        assert!(
            upload_text.contains("OMEGA"),
            "coverage should keep the end, got {upload_text:?}"
        );
        let budget = retrieval_budget(&fixture.ctx, fixture.ctx.context_budget());
        let upload_cost: usize = prepared
            .sources
            .iter()
            .filter(|s| s.shelf_id == upload.id)
            .map(tools::passage_cost)
            .sum();
        let upload_chars: usize = prepared
            .sources
            .iter()
            .filter(|s| s.shelf_id == upload.id)
            .map(|s| s.body.chars().count())
            .sum();
        let library_chars: usize = prepared
            .sources
            .iter()
            .filter(|s| s.shelf_id == fixture.shelf.id)
            .map(|s| s.body.chars().count())
            .sum();
        assert!(
            upload_chars > library_chars && upload_cost + 256 >= budget,
            "named attachment should spend the retrieval window, cost={upload_cost} budget={budget} upload={upload_chars} library={library_chars} sources={:?}",
            prepared
                .sources
                .iter()
                .map(|s| (s.shelf_id.as_str(), s.body.chars().count()))
                .collect::<Vec<_>>()
        );
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn open_shelf_file_pages_and_keeps_other_excerpts() {
        let mut body = String::from("# Encyclopedia\n\n");
        body.push_str("START unique opening.\n\n");
        body.push_str(&"The office zebra lives in the east wing.\n".repeat(800));
        body.push_str("\nEND unique closing.\n");
        let fixture = shelf_with_file("encyclopedia.md", &body).await;
        let files = super::tools::catalog(&fixture.ctx, &fixture.shelf.id);
        let mid = SourcePassage {
            sid: "S1".into(),
            document_id: files[0].id.clone(),
            shelf_id: fixture.shelf.id.clone(),
            title: "encyclopedia.md".into(),
            section: Some("East wing".into()),
            page_start: None,
            page_end: None,
            body: "The office zebra lives in the east wing.".into(),
            path: files[0].path.clone(),
            score: 1.0,
        };
        let sources = [mid];
        let tool = tool_ctx(
            &fixture.ctx,
            "t",
            &fixture.shelf.id,
            &files,
            &sources,
            1_200,
        );
        let first = super::tools::open_shelf_file(&tool, "encyclopedia.md", None);
        let tools::SourceChange::OpenWindow {
            opened: window,
            drop_sids,
        } = first.change
        else {
            panic!("expected a window, got {:?}", first.change);
        };
        assert!(!drop_sids.iter().any(|id| id == "S1"));
        assert!(window.body.contains("START"));
        assert!(!window.body.contains("END unique"));
        assert_eq!(window.sid, "S2");

        let mut after = sources.to_vec();
        tools::apply_change(
            &mut after,
            tools::SourceChange::OpenWindow {
                opened: window.clone(),
                drop_sids,
            },
        );
        assert!(after.iter().any(|s| s.sid == "S1"));
        assert!(after.iter().any(|s| s.sid == "S2"));

        let tool = tool_ctx(&fixture.ctx, "t", &fixture.shelf.id, &files, &after, 1_200);
        let second = super::tools::open_shelf_file(&tool, "encyclopedia.md", None);
        let tools::SourceChange::OpenWindow { opened: next, .. } = second.change else {
            panic!("expected the next window, got {:?}", second.change);
        };
        assert_eq!(next.sid, "S2");
        assert_ne!(next.body, window.body);
        assert!(
            next.body.contains("zebra") || next.body.contains("END"),
            "next window should move forward, got {}",
            next.body.chars().take(80).collect::<String>()
        );
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn look_around_continues_a_prefix_when_the_window_is_full() {
        let mut body = String::from("START unique opening.\n\n");
        body.push_str(&"The office zebra lives in the east wing.\n".repeat(800));
        body.push_str("\nEND unique closing.\n");
        let fixture = shelf_with_file("encyclopedia.md", &body).await;
        let files = super::tools::catalog(&fixture.ctx, &fixture.shelf.id);
        let extracted = std::fs::read_to_string(
            fixture
                .ctx
                .paths
                .extracted_path(&fixture.shelf.id, &files[0].id),
        )
        .unwrap();
        let prefix = gate::truncate_at_boundary(&extracted, 400);
        let excerpt = SourcePassage {
            sid: "S1".into(),
            document_id: files[0].id.clone(),
            shelf_id: fixture.shelf.id.clone(),
            title: "encyclopedia.md".into(),
            section: Some(super::focus::OPEN_WINDOW_START.into()),
            page_start: None,
            page_end: None,
            body: prefix,
            path: files[0].path.clone(),
            score: 2.0,
        };
        let sources = [excerpt];
        let tool = tool_ctx(&fixture.ctx, "t", &fixture.shelf.id, &files, &sources, 500);
        let call = ToolCall::function(
            "c1",
            tools::LOOK_AROUND,
            serde_json::json!({ "id": "S1" }).to_string(),
        );
        let outcome = tools::run_tool(&call, &tool).await;
        let tools::SourceChange::ReplaceOne(updated) = outcome.change else {
            panic!("expected continued excerpt, got {:?}", outcome.change);
        };
        assert_eq!(updated.sid, "S1");
        assert_eq!(
            updated.section.as_deref(),
            Some(super::focus::OPEN_WINDOW_NEXT)
        );
        assert!(!updated.body.starts_with("START unique opening."));
        assert!(updated.body.to_lowercase().contains("zebra"));
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn look_around_does_not_rewind_a_continued_window() {
        let mut body = String::from("START unique opening.\n\n");
        body.push_str(&"The office zebra lives in the east wing.\n".repeat(200));
        body.push_str("MIDDLE unique marker.\n");
        body.push_str(&"The office zebra lives in the east wing.\n".repeat(200));
        body.push_str("\nEND unique closing.\n");
        let fixture = shelf_with_file("encyclopedia.md", &body).await;
        let files = super::tools::catalog(&fixture.ctx, &fixture.shelf.id);
        let excerpt = SourcePassage {
            sid: "S1".into(),
            document_id: files[0].id.clone(),
            shelf_id: fixture.shelf.id.clone(),
            title: "encyclopedia.md".into(),
            section: Some(super::focus::OPEN_WINDOW_NEXT.into()),
            page_start: None,
            page_end: None,
            body: "MIDDLE unique marker.\nThe office zebra lives in the east wing.".into(),
            path: files[0].path.clone(),
            score: 2.0,
        };
        let sources = [excerpt];
        let tool = tool_ctx(
            &fixture.ctx,
            "t",
            &fixture.shelf.id,
            &files,
            &sources,
            12_000,
        );
        let call = ToolCall::function(
            "c1",
            tools::LOOK_AROUND,
            serde_json::json!({ "id": "S1" }).to_string(),
        );
        let outcome = tools::run_tool(&call, &tool).await;
        let tools::SourceChange::ReplaceOne(updated) = outcome.change else {
            panic!("expected continued excerpt, got {:?}", outcome.change);
        };
        assert_eq!(updated.sid, "S1");
        assert!(
            !updated.body.contains("START unique opening."),
            "a continued window should not jump back to the start, got {}",
            updated.body.chars().take(80).collect::<String>()
        );
        assert!(
            updated.body.contains("MIDDLE unique marker.")
                || updated.body.to_lowercase().contains("zebra")
                || updated.body.contains("END unique"),
            "should read onward from the current window"
        );
    }
}
