//! Chat orchestration. Every user message follows the same pipeline:
//!
//! ```text
//! user message
//!   → Tantivy (Shelf documents when one is selected, + older conversations)
//!   → Retrieval Gate
//!   → llama.cpp (house rules · shelf file index · original message · recent context · gated sources)
//!   → streamed answer with citations
//! ```
//!
//! Every answer is generated by the local model; Tantivy only supplies
//! clearly-marked source material.

pub mod conversations;
mod prompts;

use anyhow::Result;
use serde_json::json;
use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};

use crate::core::Ctx;
use crate::engine::{ChatMessage, Engine};
use crate::search::gate;
use crate::types::SourcePassage;
use conversations::{Conversations, StoredMessage};
pub use prompts::guess_message_lang;
use prompts::{
    build_system_prompt, build_user_content, format_shelf_inventory, sanitize_citations,
    shelf_file_labels,
};

const MAX_ANSWER_TOKENS: u32 = 1000;
const HISTORY_MAX_MESSAGES: usize = 12;
const HISTORY_MAX_CHARS: usize = 6_000;

pub struct ChatService {
    ctx: Arc<Ctx>,
    engine: Arc<Engine>,
    cancels: Mutex<HashMap<String, Arc<AtomicBool>>>,
}

impl ChatService {
    pub fn new(ctx: Arc<Ctx>, engine: Arc<Engine>) -> Arc<Self> {
        Arc::new(Self {
            ctx,
            engine,
            cancels: Mutex::new(HashMap::new()),
        })
    }

    pub fn cancel(&self, message_id: &str) {
        if let Some(flag) = crate::core::mutex_lock(&self.cancels).get(message_id) {
            flag.store(true, Ordering::Relaxed);
        }
    }

    #[cfg(test)]
    fn cancel_count(&self) -> usize {
        crate::core::mutex_lock(&self.cancels).len()
    }

    #[cfg(test)]
    pub(crate) fn register_cancel_for_test(&self, message_id: &str) -> Arc<AtomicBool> {
        let flag = Arc::new(AtomicBool::new(false));
        crate::core::mutex_lock(&self.cancels).insert(message_id.to_string(), flag.clone());
        flag
    }

    /// Handle one user message end to end. Emits `rebost://chat` events and
    /// returns the finished assistant message.
    pub async fn send_message(
        self: &Arc<Self>,
        thread_id: &str,
        text: &str,
        shelf_id: Option<String>,
    ) -> Result<StoredMessage> {
        let ctx = &self.ctx;
        let now = chrono::Utc::now();

        // Persist + index the user message (memory is always on).
        let user_message = StoredMessage {
            id: crate::ids::message_id(),
            role: "user".into(),
            text: text.to_string(),
            thinking: None,
            ts: now.to_rfc3339(),
            shelf_id: shelf_id.clone(),
            sources: Vec::new(),
            status: "done".into(),
        };
        Conversations::append(&ctx.paths, thread_id, &user_message)?;
        let lang = guess_message_lang(text);
        ctx.search
            .index_message(thread_id, &user_message.id, "user", text, lang, now)
            .ok();

        let assistant_id = crate::ids::message_id();
        let emit = |kind: &str, payload: serde_json::Value| {
            let mut base = json!({
                "threadId": thread_id,
                "messageId": assistant_id,
                "kind": kind,
            });
            if let (Some(base_map), Some(extra)) = (base.as_object_mut(), payload.as_object()) {
                for (k, v) in extra {
                    base_map.insert(k.clone(), v.clone());
                }
            }
            ctx.events.emit("rebost://chat", base);
        };

        emit("queued", json!({ "userMessageId": user_message.id }));

        let PreparedTurn {
            messages, sources, ..
        } = prepare_turn(ctx, thread_id, text, shelf_id.as_deref(), &user_message.id)?;

        // ── Generation (queued while Warming up…) ────────────────────────
        let cancel = Arc::new(AtomicBool::new(false));
        crate::core::mutex_lock(&self.cancels).insert(assistant_id.clone(), cancel.clone());

        let started_emit = std::sync::Once::new();
        let result = self
            .engine
            .chat_stream(&messages, 0.7, MAX_ANSWER_TOKENS, &cancel, |event| {
                started_emit.call_once(|| emit("started", json!({})));
                match event {
                    crate::engine::StreamEvent::Thinking(delta) => {
                        emit("thinking", json!({ "text": delta }));
                    }
                    crate::engine::StreamEvent::Answer(delta) => {
                        emit("delta", json!({ "text": delta }));
                    }
                    crate::engine::StreamEvent::PromoteAnswerToThinking => {
                        emit("promote", json!({}));
                    }
                }
            })
            .await;
        crate::core::mutex_lock(&self.cancels).remove(&assistant_id);

        let (answer_text, thinking_text, status) = match result {
            Ok(output) => {
                let cancelled = cancel.load(Ordering::Relaxed);
                (
                    output.answer,
                    output.thinking,
                    if cancelled { "stopped" } else { "done" },
                )
            }
            Err(error) => {
                log::error!("generation failed: {error:#}");
                emit(
                    "error",
                    json!({ "error": "The answer couldn't be generated. Try again." }),
                );
                (String::new(), String::new(), "error")
            }
        };

        // The model may cite only the source ids it received.
        let valid_ids: Vec<String> = sources.iter().map(|s| s.sid.clone()).collect();
        let cleaned = sanitize_citations(&answer_text, &valid_ids);
        let cited: Vec<SourcePassage> = sources
            .into_iter()
            .filter(|s| cleaned.contains(&format!("[{}]", s.sid)))
            .collect();

        let assistant_message = StoredMessage {
            id: assistant_id.clone(),
            role: "assistant".into(),
            text: cleaned,
            thinking: if thinking_text.is_empty() {
                None
            } else {
                Some(thinking_text)
            },
            ts: chrono::Utc::now().to_rfc3339(),
            shelf_id: shelf_id.clone(),
            sources: cited,
            status: status.to_string(),
        };
        if status != "error" {
            Conversations::append(&ctx.paths, thread_id, &assistant_message)?;
            let lang = guess_message_lang(&assistant_message.text);
            ctx.search
                .index_message(
                    thread_id,
                    &assistant_message.id,
                    "assistant",
                    &assistant_message.text,
                    lang,
                    chrono::Utc::now(),
                )
                .ok();
        }
        emit(
            "done",
            json!({ "message": assistant_message, "status": status }),
        );
        Ok(assistant_message)
    }
}

struct PreparedTurn {
    messages: Vec<ChatMessage>,
    sources: Vec<SourcePassage>,
}

fn prepare_turn(
    ctx: &Ctx,
    thread_id: &str,
    text: &str,
    shelf_id: Option<&str>,
    user_message_id: &str,
) -> Result<PreparedTurn> {
    let budget = ctx.context_budget();
    let query_tokens = ctx.search.query_tokens(text);
    let doc_hits = match shelf_id {
        Some(shelf) => ctx.search.search_passages(text, shelf, 24)?,
        None => Vec::new(),
    };
    let memory_hits = ctx.search.search_messages(text, Some(thread_id), 12)?;

    let gated_docs = gate::gate_passages(doc_hits, &query_tokens);
    let gated_memory = gate::gate_messages(memory_hits, &query_tokens);
    let (sources, memory) = gate::fit_to_budget(gated_docs, gated_memory, budget);

    let (shelf_name, shelf_inventory) = shelf_prompt_bits(ctx, shelf_id);
    let house_rules = crate::core::read_lock(&ctx.settings).house_rules.clone();
    let system = build_system_prompt(
        &house_rules,
        shelf_name.as_deref(),
        shelf_inventory.as_deref(),
        !sources.is_empty(),
        !memory.is_empty(),
    );

    let mut messages = vec![ChatMessage {
        role: "system".into(),
        content: system,
    }];
    for previous in Conversations::recent_history(
        &ctx.paths,
        thread_id,
        HISTORY_MAX_MESSAGES,
        HISTORY_MAX_CHARS,
    ) {
        if previous.id == user_message_id {
            continue;
        }
        messages.push(ChatMessage {
            role: previous.role.clone(),
            content: gate::truncate_at_boundary(&previous.text, 1600),
        });
    }
    messages.push(ChatMessage {
        role: "user".into(),
        content: build_user_content(text, &sources, &memory),
    });
    Ok(PreparedTurn { messages, sources })
}

fn shelf_prompt_bits(ctx: &Ctx, shelf_id: Option<&str>) -> (Option<String>, Option<String>) {
    let Some(id) = shelf_id else {
        return (None, None);
    };
    let library = crate::core::read_lock(&ctx.library);
    let Some(name) = library.shelf(id).map(|s| s.name.clone()) else {
        return (None, None);
    };
    let docs = library.documents(id);
    let labels = shelf_file_labels(
        docs.iter()
            .map(|d| (d.file_name.as_str(), d.rel_path.as_str())),
    );
    let inventory = format_shelf_inventory(&name, &labels);
    (Some(name), Some(inventory))
}

#[cfg(test)]
mod cancel_tests {
    use super::*;
    use crate::core::NoopEvents;
    use crate::ingest::extract::ExtractorSettings;
    use crate::paths::Paths;
    use std::sync::atomic::Ordering;

    struct Bundle {
        chat: Arc<ChatService>,
        _dir: tempfile::TempDir,
    }

    fn test_chat() -> Bundle {
        let dir = tempfile::tempdir().unwrap();
        let paths = Paths::new(dir.path().join("appdata"));
        let ctx = Ctx::new(paths, Arc::new(NoopEvents), ExtractorSettings::default()).unwrap();
        let engine = Engine::new(ctx.clone());
        Bundle {
            chat: ChatService::new(ctx, engine),
            _dir: dir,
        }
    }

    #[test]
    fn cancel_unknown_id_is_silent() {
        let bundle = test_chat();
        bundle.chat.cancel("no-such-message");
        assert_eq!(bundle.chat.cancel_count(), 0);
    }

    #[test]
    fn cancel_sets_registered_flag() {
        let bundle = test_chat();
        let flag = bundle.chat.register_cancel_for_test("m1");
        assert!(!flag.load(Ordering::Relaxed));
        bundle.chat.cancel("m1");
        assert!(flag.load(Ordering::Relaxed));
    }
}

#[cfg(test)]
mod prepare_tests {
    use super::*;
    use crate::core::NoopEvents;
    use crate::ingest::extract::ExtractorSettings;
    use crate::ingest::ProcessJob;
    use crate::paths::Paths;
    use crate::types::SourceType;

    #[tokio::test(flavor = "multi_thread")]
    async fn prepare_turn_puts_shelf_passages_in_the_prompt() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("Shelves");
        let paths = Paths::new(dir.path().join("appdata"));
        let ctx = Ctx::new(paths, Arc::new(NoopEvents), ExtractorSettings::default()).unwrap();
        let shelf = {
            let mut library = crate::core::write_lock(&ctx.library);
            library.create_shelf(&ctx.paths, "Notes", &root).unwrap()
        };
        let file = dir.path().join("handbook.md");
        std::fs::write(
            &file,
            "# Staff handbook\n\nThe office kitchen is restocked every Tuesday morning.\n",
        )
        .unwrap();
        let copied = crate::shelf::import_into_shelf(&shelf, &[file]).unwrap().1;
        let abs = copied.into_iter().next().unwrap();
        let rel = abs
            .strip_prefix(&shelf.managed_path)
            .unwrap()
            .to_string_lossy()
            .to_string();
        crate::ingest::process_file(
            &ctx,
            &ProcessJob {
                shelf_id: shelf.id.clone(),
                source_id: crate::shelf::Shelf::IMPORTED_SOURCE.to_string(),
                source_type: SourceType::Imported,
                source_label: "Imported".into(),
                abs_path: abs,
                rel_path: rel,
                force: false,
            },
        )
        .await
        .unwrap();

        let thread = Conversations::create(&ctx.paths, Some(shelf.id.clone())).unwrap();
        let prepared = prepare_turn(
            &ctx,
            &thread.id,
            "When is the kitchen restocked?",
            Some(&shelf.id),
            "m_none",
        )
        .unwrap();
        assert!(
            !prepared.sources.is_empty(),
            "expected retrieved passages, got none"
        );
        let user = prepared
            .messages
            .iter()
            .find(|m| m.role == "user")
            .expect("user message");
        assert!(
            user.content.to_lowercase().contains("tuesday")
                || prepared
                    .sources
                    .iter()
                    .any(|s| s.body.to_lowercase().contains("tuesday")),
            "prompt should carry the handbook passage"
        );
        let system = &prepared.messages[0].content;
        assert!(system.contains("Notes"));
    }
}
